### ISSUE TITLE
ActivityCompletionClient's completeExceptionally doesn't work with ApplicationFailure 

### ISSUE THREAD

**Issue by rubyhfu** [temporalio/temporal#1186]
## Expected Behavior
Expected no error logs using completionClient.completeExceptionally with any exception but it throws errors when used with ApplicationFailure.newNonRetryableFailure and ApplicationFailure.newFailure.

## Actual Behavior
[reactor-http-nio-1] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
java.lang.IllegalStateException: converter not set
	at io.temporal.common.converter.EncodedValues.toPayloads(EncodedValues.java:48) ~[temporal-sdk-1.0.0.jar:?]
	at io.temporal.failure.FailureConverter.exceptionToFailureNoUnwrapping(FailureConverter.java:210) ~[temporal-sdk-1.0.0.jar:?]
	at io.temporal.failure.FailureConverter.exceptionToFailure(FailureConverter.java:184) ~[temporal-sdk-1.0.0.jar:?]
	at io.temporal.internal.external.ManualActivityCompletionClientImpl.fail(ManualActivityCompletionClientImpl.java:163) ~[temporal-sdk-1.0.0.jar:?]
	at io.temporal.internal.sync.ActivityCompletionClientImpl.completeExceptionally(ActivityCompletionClientImpl.java:49) ~[temporal-sdk-1.0.0.jar:?]

## Steps to Reproduce the Problem

  1. Create a workflow with a simple activity, inject an ActivityCompletionClient into the activity
  2. Inside the activity's async process, add:
  completionClient.completeExceptionally(taskToken, ApplicationFailure.newNonRetryableFailure("xxx", "xxx", "xxx"));
  3. Invoke the workflow using TestWorkflowEnv, the above error logs should be printed

## Specifications

  - Version: temporal-sdk-1.0.0
  - Platform: macOS Big Sur

**Comment by mfateev** [comment]
I was able to reproduce the problem. Thanks a lot for reporting!
