### ISSUE TITLE
tctl does not allow passing primitive values as input parameters to workflow start

### ISSUE THREAD

**Issue by robzienert** [temporalio/temporal#1585]
## Expected Behavior
I have a workflow that has two arguments, a JSON document and a string value. I would expect that passing `--input foo` would work as-is, since strings and other primitive types are considered valid JSON documents on their own.

## Actual Behavior
tctl rejects the request, saying that the input must be valid JSON.

```
TEMPORAL_CLI_SHOW_STACKS=1 ./scripts/tctl.sh wf start --tq foo --w robztest --wt StageContextCloudOperationRunner --if test.json -i "resizeServerGroup" --et 120
Error: Input is not a valid JSON.
Error Details: invalid character 'r' looking for beginning of value
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack(0xd, 0x0, 0x0)
	runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x25
go.temporal.io/server/tools/cli.printError(0x2ae7338, 0x1a, 0x2d9d940, 0xc00046f950)
	go.temporal.io/server/tools/cli/util.go:386 +0x2be
go.temporal.io/server/tools/cli.ErrorAndExit(0x2ae7338, 0x1a, 0x2d9d940, 0xc00046f950)
	go.temporal.io/server/tools/cli/util.go:397 +0x49
go.temporal.io/server/tools/cli.processJSONInput(0xc00022c9a0, 0x2ade3a5)
	go.temporal.io/server/tools/cli/util.go:618 +0x352
go.temporal.io/server/tools/cli.startWorkflowHelper(0xc00022c9a0, 0x0)
	go.temporal.io/server/tools/cli/workflowCommands.go:208 +0x245
go.temporal.io/server/tools/cli.StartWorkflow(...)
	go.temporal.io/server/tools/cli/workflowCommands.go:176
go.temporal.io/server/tools/cli.newWorkflowCommands.func3(0xc00022c9a0)
	go.temporal.io/server/tools/cli/workflow.go:57 +0x30
github.com/urfave/cli.HandleAction(0x2734000, 0x2b6a478, 0xc00022c9a0, 0xc00022c9a0, 0x0)
	github.com/urfave/cli@v1.22.5/app.go:526 +0x59
github.com/urfave/cli.Command.Run(0x2abdd24, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2af22a7, 0x1e, 0x0, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x579
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000496540, 0xc00022c6e0, 0x0, 0x0)
	github.com/urfave/cli@v1.22.5/app.go:405 +0x914
github.com/urfave/cli.Command.startApp(0x2ac4d34, 0x8, 0x0, 0x0, 0xc000b44420, 0x1, 0x1, 0x2ae50f8, 0x19, 0x0, ...)
	github.com/urfave/cli@v1.22.5/command.go:372 +0x7ff
github.com/urfave/cli.Command.Run(0x2ac4d34, 0x8, 0x0, 0x0, 0xc000b44420, 0x1, 0x1, 0x2ae50f8, 0x19, 0x0, ...)
	github.com/urfave/cli@v1.22.5/command.go:102 +0x9d4
github.com/urfave/cli.(*App).Run(0xc0004961c0, 0xc0001aa000, 0x11, 0x12, 0x0, 0x0)
	github.com/urfave/cli@v1.22.5/app.go:277 +0x808
main.main()
	command-line-arguments/main.go:37 +0x4e
```

## Steps to Reproduce the Problem

  1. Define a workflow that takes a primitive value as an input parameter.
  1. Attempt to start it from tctl

## Specifications

  - Version: 1.9.1
  - Platform: OSX

**Comment by robzienert** [comment]
Works as desired -- string values must be double-quoted to be parsed correctly.
