### ISSUE TITLE
Temporal Java SDK causes exceptions when being run on JDK 16 (illegal access to internal field of Throwable class)

### ISSUE THREAD

**Issue by mattes3** [temporalio/temporal#1868]
## Expected Behavior

I expect Temporal Java SDK to run with JDK 16.

## Actual Behavior

Temporal's internal exception handling code (the static initializer block of class `CheckedExceptionWrapper`) produces additional exceptions when it is run under JDK 16!

This is because Temporal accesses a private member `Throwable.cause` by means of reflection which is now denied by default (new behaviour in JDK 16).

See the exact description of the change in JDK 16 here: https://www.oracle.com/java/technologies/javase/16-relnotes.html#JDK-8256299

## Workaround for now

Such code can be made to run on JDK 16 by specifying `--illegal-access=permit` on the `java` command line. That option will, however, be removed in a future release of the JDK.

## Steps to Reproduce the Problem

  1. Run a Temporal workflow where one activity causes an exception.
  1. Watch the exception handling code crash with a new RuntimeException:

```
java.lang.RuntimeException: Failure processing workflow task. WorkflowId=REDACTED, RunId=REDACTED
at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.wrapFailure(WorkflowWorker.java:337)
at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.wrapFailure(WorkflowWorker.java:275)
at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:79)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)


==== this is the crime scene ===

Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.temporal.internal.common.CheckedExceptionWrapper
at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:203)

=========================

at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTask(ReplayWorkflowRunTaskHandler.java:150)
at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithEmbeddedQuery(ReplayWorkflowTaskHandler.java:202)
at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:112)
at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:309)
at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:275)
at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
```

## Specifications

  - Version: Temporal 1.10.5 with Temporal Java SDK 1.0.0
  - Platform: https://adoptopenjdk.net/ JDK 16 on Debian Linux

**Comment by mattes3** [comment]
Oops, I just realized that this can be solved simply by upgrading the Temporal SDK for Java to version 1.2.0. Sorry, folks, I should have tried this first!

**Comment by yiminc** [comment]
Glad that the problem is solved.
