### ISSUE TITLE
Unable to query completed workflow

### ISSUE THREAD

**Issue by datoslabs** [temporalio/temporal#1869]
Hi,

I am trying to evaluate Temporal for my project.  I am fairly new to Temporal; I was under the impression that I would be able to query against a workflow in completed status as per [Custom query on a terminated workflow returns error](https://community.temporal.io/t/custom-query-on-a-terminated-workflow-returns-error/1756) discussion.  

In my test, if I use the same `workflowStub` instance that started the workflow, I was able to query the workflow after I wait for its completion using `Thread.sleep()`; however, if I exit and restart `worker` as well as reinstantiate a new `workflowStub` with the same `workflowId`, I receive `IllegalStateException`.  Is querying the workflow long after it's completed/terminated not supported?

## Expected Behavior
After a workflow is completed, user should be able to query the workflow with a new workflowStub.

## Actual Behavior
Received the following error:
```
Exception in thread "main" java.lang.IllegalStateException: Null workflowId. Was workflow started?
	at io.temporal.internal.sync.WorkflowStubImpl.checkStarted(WorkflowStubImpl.java:388)
	at io.temporal.internal.sync.WorkflowStubImpl.query(WorkflowStubImpl.java:337)
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.queryWorkflow(WorkflowInvocationHandler.java:309)
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:272)
	at io.temporal.internal.sync.WorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:178)
	at com.sun.proxy.$Proxy10.getCurrentState(Unknown Source)
	at ai.crowdlytics.orchestration.temporal.workflow.Test.main(Test.java:75)
```

## Steps to Reproduce the Problem

  1.  Start a workflow
  2.  Use `Thread.sleep` to wait until workflow is completed, using the same `workflowStub` instance (that started the workflow execution) to query the workflow returns successfully with expected results.
  3.  Terminate worker and client.
  4.  Initiate a new `WorkerFactory` (ie `factory.start()`), new `workflowStub` instance with the same `workflowId ` and execute the workflow query method, this time it fails with the above stack trace.

## Specifications

  - Version: 1.2.0
  - Platform: client: Java SDK, server: docker-compose -f docker-compose-postgres.yml up

**Comment by datoslabs** [comment]
Please disregard, I figured out what I did wrong.  For an existing workflow, I should instantiate the `workflowStub` with:

`client.newWorkflowStub(DSLWorkflow.class, workflowId);`

Instead, I was instantiating the `workflowStub` with:

```
client.newWorkflowStub(DSLWorkflow.class,
	WorkflowOptions.newBuilder().setWorkflowId(workflowId).setTaskQueue(TASK_QUEUE).build());
```
which should only be used to start a new workflow.
