### ISSUE TITLE
temporal-history nil pointer dereference error on boot.

### ISSUE THREAD

**Issue by salzr** [temporalio/temporal#1885]
## Expected Behavior
temporal-history service in **RUNNING** status.

## Actual Behavior
temporal-history service currently in **CrashLoopBackOff** 
It was working as expected for quite some time then ran into the following exception.

`{"level":"info","ts":"2021-09-02T16:51:40.748Z","msg":"Acquired shard","service":"history","shard-id":285,"address":"1.2.3.4.5:7234","shard-item":"0xc0047f1080","logging-call-at":"shardContext.go:1273"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13bc31e]

goroutine 12236 [running]:
go.temporal.io/server/common/persistence.(*statsComputer).computeMutableStateStats(0xc00472b670, 0xc000727c08, 0xc004199680)
	/temporal/common/persistence/statsComputer.go:70 +0x33e
go.temporal.io/server/common/persistence.(*executionManagerImpl).GetWorkflowExecution(0xc00472b650, 0xc0046ed590, 0xc000406d20, 0x13, 0x2177eb2)
	/temporal/common/persistence/executionStore.go:105 +0x279` 

Because of this workflows are stuck.  Fails to create new or cancel existing workflows.

## Steps to Reproduce the Problem

  1. Unknown the root cause.  Continues to fail post aquiring the same shard-id.

## Specifications

  - Version: temporalio/server:0.29.0
  - Platform: K8s

**Comment by yiminc** [comment]
@salzr Could you try latest server version 1.12.0
