### ISSUE TITLE
CLI SIGSEGV 

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#228]
```
maxpro:temporal maxim$ ./tctl -do default workflow list -op
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x522dbf7]

goroutine 1 [running]:
github.com/temporalio/temporal/tools/cli.appendWorkflowExecutionsToTable(0xc0004e0780, 0xc000010028, 0x1, 0x1, 0x15fd4b0000000001)
	/Users/maxim/temporal/temporal/tools/cli/workflowCommands.go:1065 +0x707
github.com/temporalio/temporal/tools/cli.listWorkflow.func1(0x0, 0x0, 0x0, 0xc000172280, 0x574cd7c, 0x57493d7, 0x4)
	/Users/maxim/temporal/temporal/tools/cli/workflowCommands.go:1032 +0x288
github.com/temporalio/temporal/tools/cli.ListWorkflow(0xc0001ecc60)
	/Users/maxim/temporal/temporal/tools/cli/workflowCommands.go:571 +0x263
github.com/temporalio/temporal/tools/cli.newWorkflowCommands.func8(0xc0001ecc60)
	/Users/maxim/temporal/temporal/tools/cli/workflow.go:140 +0x2b
github.com/urfave/cli.HandleAction(0x54219a0, 0x57df450, 0xc0001ecc60, 0xc0000e6a00, 0x0)
	/Users/maxim/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.Command.Run(0x57494b7, 0x4, 0x0, 0x0, 0xc00019e780, 0x1, 0x1, 0x578938c, 0x27, 0x0, ...)
	/Users/maxim/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x991
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000532000, 0xc0001ec580, 0x0, 0x0)
	/Users/maxim/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:379 +0x7fa
github.com/urfave/cli.Command.startApp(0x574ec9a, 0x8, 0x0, 0x0, 0xc00019ed50, 0x1, 0x1, 0x5769af0, 0x19, 0x0, ...)
	/Users/maxim/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:298 +0x817
github.com/urfave/cli.Command.Run(0x574ec9a, 0x8, 0x0, 0x0, 0xc00019ed50, 0x1, 0x1, 0x5769af0, 0x19, 0x0, ...)
	/Users/maxim/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:98 +0x11dc
github.com/urfave/cli.(*App).Run(0xc000181a00, 0xc0000be060, 0x6, 0x6, 0x0, 0x0)
	/Users/maxim/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6ab
main.main()
	/Users/maxim/temporal/temporal/cmd/tools/cli/main.go:33 +0x4b
maxpro:temporal maxim$
```

**Comment by mfateev** [comment]
Without -op option it works fine:
```
maxpro:temporal maxim$ ./tctl -do default workflow list
             WORKFLOW TYPE            |  WORKFLOW ID  |                RUN ID                | START TIME | EXECUTION TIME | END TIME
  ...etingWorkflow::greetPeriodically | HelloPeriodic | 6227ff9f-0687-4c5b-a794-084022807bb5 | 21:31:41   | 21:31:41       | 21:32:02
  ...etingWorkflow::greetPeriodically | HelloPeriodic | 36a97c76-050f-4647-96b9-1f9a04b62a78 | 21:30:43   | 21:30:43       | 21:31:41
  ...etingWorkflow::greetPeriodically | HelloPeriodic | 2cf49a95-b1fb-475a-8789-8e97e9a4d061 | 21:29:44   | 21:29:44       | 21:30:43
  ...etingWorkflow::greetPeriodically | HelloPeriodic | aab730c8-c849-43b3-9888-7978160551e4 | 21:28:38   | 21:28:38       | 21:29:44
  ...etingWorkflow::greetPeriodically | HelloPeriodic | c4a965bd-4c67-4f63-be77-a8ab997049c2 | 21:27:44   | 21:27:44       | 21:28:38
  ...etingWorkflow::greetPeriodically | HelloPeriodic | 3d5a3052-578a-4fbc-aaab-d0b5ebbf9821 | 21:26:58   | 21:26:58       | 21:27:44
  ...etingWorkflow::greetPeriodically | HelloPeriodic | 85b12d1a-1aae-4c64-aa68-6daea4a011d3 | 21:26:15   | 21:26:15       | 21:26:58
  ...etingWorkflow::greetPeriodically | HelloCron     | f5eb0f6a-6101-47ff-9cdf-2c020b10c3a5 | 21:25:55   | 21:25:57       | 21:30:57
  ...etingWorkflow::greetPeriodically | HelloPeriodic | a409edcd-773f-4f13-a26a-3b7ca2ea2cda | 21:25:28   | 21:25:28       | 21:26:15
  ...etingWorkflow::greetPeriodically | HelloPeriodic | 11be5cd3-e1fe-43a3-b9a7-3ce1bdd9e7b9 | 21:24:31   | 21:24:31       | 21:25:28
```
