### ISSUE TITLE
nil pointer in temporal-sql-tool update

### ISSUE THREAD

**Issue by vikstrous2** [temporalio/temporal#2294]
## Expected Behavior
Graceful error handling

## Actual Behavior
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xebe954]

goroutine 1 [running]:
go.temporal.io/server/tools/sql.(*Connection).Close(0x0)
	/temporal/tools/sql/conn.go:120 +0x14
panic({0xf78e80, 0x1a77a30})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
go.temporal.io/server/tools/sql.(*Connection).ReadSchemaVersion(0xc000411d30)
	/temporal/tools/sql/conn.go:65 +0x14
go.temporal.io/server/tools/common/schema.(*UpdateTask).Run(0xc00071f608)
	/temporal/tools/common/schema/updatetask.go:106 +0x223
go.temporal.io/server/tools/common/schema.Update(0xc000411d30, {0x12ed200, 0x0}, {0x12e8ed8, 0xc000411d30})
	/temporal/tools/common/schema/handler.go:48 +0x98
go.temporal.io/server/tools/sql.updateSchema(0x7fea47570060, {0x12e8ed8, 0xc000411d30})
	/temporal/tools/sql/handler.go:76 +0x51a
go.temporal.io/server/tools/sql.cliHandler(0x2, 0x1126110, {0x12e8ed8, 0xc000411d30})
	/temporal/tools/sql/main.go:48 +0x56
go.temporal.io/server/tools/sql.BuildCLIOptions.func2(0xc0000b66e0)
	/temporal/tools/sql/main.go:185 +0x2b
github.com/urfave/cli.HandleAction({0xf317a0, 0xc000411d50}, 0xd)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:526 +0x50
github.com/urfave/cli.Command.Run({{0x10af830, 0xd}, {0x0, 0x0}, {0xc000411d90, 0x1, 0x1}, {0x10dcff0, 0x27}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc00045e8c0, {0xc00012c040, 0x4, 0x4})
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x705
go.temporal.io/server/tools/sql.RunTool({0xc00012c040, 0x4, 0x4})
	/temporal/tools/sql/main.go:42 +0x3c
main.main()
	/temporal/cmd/tools/sql/main.go:36 +0x2e
```

## Steps to Reproduce the Problem

Try to run migrations:
```
export SQL_PLUGIN=postgres
export SQL_HOST=127.0.0.1
export SQL_PORT=5432
export SQL_USER=temporal
SQL_DATABASE=temporal temporal-sql-tool update --schema-dir /etc/temporal/schema/postgresql/v96/temporal/versioned
```

I'm not sure if the issue is that the migrations had already been run or something else, but this seems to panic randomly, so hopefully this is enough context.

## Specifications

  - Version: 1.13.1
  - Platform: docker/kubernetes

**Comment by vikstrous2** [comment]
Update: actually, this seems to happen BEFORE migrations succeed, so maybe it just has a random chance of happening. The last log entry before the panic is:
```
UpdateSchemeTask started	{"config": {"DBName":"","TargetVersion":"","SchemaDir":"/etc/temporal/schema/postgresql/v96/temporal/versioned","IsDryRun":false}, "logging-call-at": "updatetask.go:98"}
```

**Comment by yiminc** [comment]
https://github.com/temporalio/temporal/pull/2250
