### ISSUE TITLE
Invalid TLS config may crash service during service start

### ISSUE THREAD

**Issue by yux0** [temporalio/temporal#2448]
## Expected Behavior
The service start should return an error to indicate the invalid tls config.

## Actual Behavior
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x24f6324]

goroutine 1 [running]:
go.temporal.io/server/common/rpc/encryption.newServerTLSConfig({0x303fa18, 0xc00042e2a0}, {0x300f7a0, 0xc000ccc040}, 0x0, {0x303f7d8, 0xc000489750})
        /Users/yx/release/temporal/common/rpc/encryption/localStoreTlsProvider.go:255 +0x144
go.temporal.io/server/common/rpc/encryption.(*localStoreTlsProvider).GetFrontendServerConfig.func1()
        /Users/yx/release/temporal/common/rpc/encryption/localStoreTlsProvider.go:162 +0x4c
go.temporal.io/server/common/rpc/encryption.(*localStoreTlsProvider).getOrCreateConfig(0xc0004f2480, 0xc0004f24f8, 0xc000ebba58, 0x19)
        /Users/yx/release/temporal/common/rpc/encryption/localStoreTlsProvider.go:232 +0x102
go.temporal.io/server/common/rpc/encryption.(*localStoreTlsProvider).GetFrontendServerConfig(0xc0004d9e30)
        /Users/yx/release/temporal/common/rpc/encryption/localStoreTlsProvider.go:159 +0x77
go.temporal.io/server/common/rpc.(*RPCFactory).GetFrontendGRPCServerOptions(0x0)
        /Users/yx/release/temporal/common/rpc/rpc.go:74 +0x36
`

## Steps to Reproduce the Problem
  1. Add invalid tls config:
  ``global:
  tls:
    frontend:
      client:
        forceTLS: true``
  2. start frontend service

## Specifications

  - Version: test locally with v.1.14
  - Platform: mac os

**Comment by yux0** [comment]
The Frontend TLS uses config.Frontend: https://github.com/temporalio/temporal/blob/master/common/rpc/encryption/localStoreTlsProvider.go#L90 to determine if TLS is enable

The TLS initialization use: https://github.com/temporalio/temporal/blob/master/common/config/config.go#L487 to determine if TLS is enable.

Panic:
https://github.com/temporalio/temporal/blob/master/common/rpc/encryption/localStoreTlsProvider.go#L255
