### ISSUE TITLE
INVALID_ARGUMENT thrown when trying to complete an activity thats already completed

### ISSUE THREAD

**Issue by darewreck54** [temporalio/temporal#2538]
The exception below is thrown when trying to complete an activity.  

based on this thread https://community.temporal.io/t/reasonable-values-for-task-pollers/2257/2?u=darewreck it states that this could be due to 

```
due to activity timeouts. When an activity takes longer to complete than its StartToClose timeout the call to the service with the activity result is rejected with this message.
```

In my case, the argument gets thrown because the activity is already completed.   Shouldn't another exception be thrown vs. `INVALID_ARGUMENT`

```
"io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Cannot locate Activity ScheduleID
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskCompletedById(WorkflowServiceGrpc.java:2762)
	at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.complete(ManualActivityCompletionClientImpl.java:135)
	... 85 common frames omitted
Wrapped by: io.temporal.client.ActivityCompletionFailureException: ActivityId=2be5aea6-d792-3e8d-b0ee-9117f6b246a8
	at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.processException(ManualActivityCompletionClientImpl.java:294)
	at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.complete(ManualActivityCompletionClientImpl.java:137)
	at io.temporal.internal.sync.ActivityCompletionClientImpl.complete(ActivityCompletionClientImpl.java:53)
	at jdk.internal.reflect.GeneratedMethodAccessor454.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.temporal.internal.WorkflowThreadMarker.lambda$protectFromWorkflowThread$1(WorkflowThreadMarker.java:80)
	at com.sun.proxy.$Proxy112.complete(Unknown Source)
```

**Comment by Spikhalskiy** [comment]
It looks that NOT_FOUND or maybe FAILED_PRECONDITION is indeed a more correct code for this situation.
Also, Temporal Server may return a better message to help users understand what could be the reason of the absent ScheduleIdD. Maybe something like "io.grpc.StatusRuntimeException: NOT_FOUND: Cannot locate in-progress Activity with the ScheduleID, activity was never scheduled or already closed".

**Comment by jbreiding** [comment]
@Spikhalskiy This all makes sense. Changing the grpc code to `FAILED_PRECONDITION` or `NOT_FOUND`, would the SDK respond differently in either case?

`NOT_FOUND` seems to make the most sense, this piece of the suggested message seems off `it was never scheduled or already closed`.

Given the SDK has the information about the activity if the response code is `NOT_FOUND` the sdk could lookup the activities last state and provide the exact cause for the activity and schedule ID not being in mutable state?

**Comment by Spikhalskiy** [comment]
@jbreiding 
> Changing the grpc code to FAILED_PRECONDITION or NOT_FOUND, would the SDK respond differently in either case?

No, SDK will just have `io.temporal.client.ActivityCompletionFailureException`, which is a correct one, but the underlying raw gRPC exception will make more sense for the users.

> Given the SDK has the information about the activity if the response code is NOT_FOUND the sdk could lookup the activities last state and provide the exact cause for the activity and schedule ID not being in mutable state?

It's not given. When we use ManualActivityCompletionClientImpl we are even outside of Temporal worker. The only thing that we have is basically an activityId and temporal API. 
But even inside Temporal SDK, there is no way for SDK to figure out what happened here.
So, Server has to provide enough clues in the error here for users to don't be lost.

**Comment by jbreiding** [comment]
I will update the error code and message.

The server during this api call only has the context for lookup in mutable state. Perhaps instead of `it was never scheduled or already closed.` the error message could suggest to look through workflow execution history to determine activity state?

**Comment by Spikhalskiy** [comment]
> Perhaps instead of it was never scheduled or already closed. the error message could suggest to look through workflow execution history to determine activity state?

This is a more safe and 100% correct message, yeah. I was just thinking that we may give users the 99% (because I believe that in vast majority of cases these two reasons will be causing the absence of activity in the mutable state) message, but that may be immediately actionable and clear for them.
