### ISSUE TITLE
Potential race of direct query and scheduling of the first workflow tasks of the workflow

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/temporal#2824]
Some users reports a spike in the following Query failures **after an upgrade from 1.14 to 1.15.2**:

```
INVALID_ARGUMENT: java.lang.IllegalArgumentException: Unknown query type: getReservation, knownTypes=[]
	at io.temporal.internal.sync.QueryDispatcher.handleQuery(QueryDispatcher.java:79)
	at io.temporal.internal.sync.SyncWorkflowContext.handleQuery(SyncWorkflowContext.java:275)
	at io.temporal.internal.sync.WorkflowExecuteRunnable.handleQuery(WorkflowExecuteRunnable.java:118)
	at io.temporal.internal.sync.SyncWorkflow.query(SyncWorkflow.java:187)
	at io.temporal.internal.replay.ReplayWorkflowExecutor.query(ReplayWorkflowExecutor.java:136)
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleQueryWorkflowTask(ReplayWorkflowRunTaskHandler.java:241)
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithQuery(ReplayWorkflowTaskHandler.java:117)
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:97)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handleTask(WorkflowWorker.java:277)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:231)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:173)
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

It's a direct (legacy) Query path. This typically happens when a direct query comes to a worker with a history not containing a single completed Workflow Task like it's described in #2300. 
There are no cron, no workflow failures, and no Workflow Task failures as confirmed by the user. Also, the issue happens right after the workflow calls Continue-as-New.

It likely means that the query is getting dispatched to the worker before scheduling a first Workflow Task after Continue-as-New. But this should never happen. Temporal always schedules a first Workflow Task immediately after a Workflow Start or Continue-as-New and the Query should be buffered as a part of this first Workflow Task and not being sent as a direct Query.

**Comment by Spikhalskiy** [comment]
Closed by #2826
