### ISSUE TITLE
Listing Tasklist partitions crashes server

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#320]
```
./tctl --ns temporal-system tl list-partition --tl temporal-sys-history-scanner-tasklist-0
```

fails with:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x41ef846]

goroutine 83623 [running]:
go.temporal.io/temporal-proto/tasklist.(*TaskListPartitionMetadata).MarshalToSizedBuffer(0x0, 0xc0016fe000, 0xfa0, 0xfa0, 0x58fd748, 0xc00106d8f8, 0x404dcbc)
	/Users/samar/go/pkg/mod/go.temporal.io/temporal-proto@v0.20.23-0.20200419215242-d6f5d8fa6b15/tasklist/message.pb.go:611 +0x26
github.com/temporalio/temporal/.gen/proto/matchingservice.(*ListTaskListPartitionsResponse).MarshalToSizedBuffer(0xc00165c6c0, 0xc0016fe000, 0xfa0, 0xfa0, 0x400c443, 0x570fc80, 0x58fd700)
	/Users/samar/projects/temporal/src/github.com/temporalio/temporal/.gen/proto/matchingservice/request_response.pb.go:2479 +0xc3
github.com/temporalio/temporal/.gen/proto/matchingservice.(*ListTaskListPartitionsResponse).Marshal(0xc00165c6c0, 0x58fd700, 0xc00165c6c0, 0x7f1db68, 0xc00165c6c0, 0xc00106da01)
	/Users/samar/projects/temporal/src/github.com/temporalio/temporal/.gen/proto/matchingservice/request_response.pb.go:2459 +0x7a
google.golang.org/grpc/encoding/proto.codec.Marshal(0x58fd700, 0xc00165c6c0, 0x6ccefa0, 0x7a4e7d0, 0x400afcb, 0xc000032000, 0x5726820)
	/Users/samar/go/pkg/mod/google.golang.org/grpc@v1.28.0/encoding/proto/proto.go:70 +0x193
google.golang.org/grpc.encode(0xf846440, 0x6cf9850, 0x58fd700, 0xc00165c6c0, 0x6cf9850, 0x0, 0xc00106db18, 0x5356011, 0x0)
	/Users/samar/go/pkg/mod/google.golang.org/grpc@v1.28.0/rpc_util.go:545 +0x52
google.golang.org/grpc.(*Server).sendResponse(0xc000f7a340, 0x5e22840, 0xc000840600, 0xc000b44200, 0x58fd700, 0xc00165c6c0, 0x0, 0x0, 0xc001633d4e, 0x0, ...)
	/Users/samar/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:869 +0x89
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000f7a340, 0x5e22840, 0xc000840600, 0xc000b44200, 0xc00074eab0, 0x6cb7e60, 0x0, 0x0, 0x0)
	/Users/samar/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1117 +0x5fb
google.golang.org/grpc.(*Server).handleStream(0xc000f7a340, 0x5e22840, 0xc000840600, 0xc000b44200, 0x0)
	/Users/samar/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1405 +0xcc9
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0009bfca0, 0xc000f7a340, 0x5e22840, 0xc000840600, 0xc000b44200)
	/Users/samar/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/samar/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa1
```

**Comment by markmark206** [comment]
i believe this to be fixed, with this update: https://github.com/temporalio/temporal/pull/639
