### ISSUE TITLE
CLI: "workflow run" times out after 2 minutes.

### ISSUE THREAD

**Issue by firdaus** [temporalio/temporal#329]
```
 docker run --network=host --rm temporalio/tctl:0.21.1 workflow run --tasklist TestTaskList --workflow_type TestWorkflow_test --execution_timeout 100000000000 --input '{}'
Running execution:
  Workflow Id : 3fa0b7f8-dca7-419a-9155-45c7aa1c28e6
  Run Id      : 2aaf983b-e274-4978-9cf2-5cfd763e9b06
  Type        : TestWorkflow_test
  Namespace   : default
  Task List   : TestTaskList
  Args        : {}
Progress:
  1, 2020-04-26T16:52:56Z, WorkflowExecutionStarted
  2, 2020-04-26T16:52:56Z, DecisionTaskScheduled
  3, 2020-04-26T16:52:56Z, DecisionTaskStarted
  4, 2020-04-26T16:52:56Z, DecisionTaskCompleted
  5, 2020-04-26T16:52:56Z, ActivityTaskScheduled
  6, 2020-04-26T16:52:56Z, ActivityTaskStarted
  7, 2020-04-26T16:53:13Z, ActivityTaskCompleted
  8, 2020-04-26T16:53:13Z, DecisionTaskScheduled
  9, 2020-04-26T16:53:13Z, DecisionTaskStarted
  10, 2020-04-26T16:53:13Z, DecisionTaskCompleted
  11, 2020-04-26T16:53:13Z, TimerStarted

Time elapse: 120s
Error: Unable to read event.
Error Details: context deadline exceeded
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
```

**Comment by firdaus** [comment]
This is the stack trace if it helps:

```
Stack trace:
goroutine 26 [running]:
runtime/debug.Stack(0xd, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/temporalio/temporal/tools/cli.ErrorAndExit(0x1a3fd32, 0x15, 0x1da4d80, 0xc00000c100)
	/temporal/tools/cli/util.go:513 +0x2ad
github.com/temporalio/temporal/tools/cli.printWorkflowProgress.func1(0x7f9f8bdb4690, 0xc0006646c0, 0x1ddc380, 0xc00009db00, 0xc00008a750, 0x24, 0xc00008b200, 0x24, 0xc000042b40, 0x0, ...)
	/temporal/tools/cli/workflowCommands.go:376 +0x558
created by github.com/temporalio/temporal/tools/cli.printWorkflowProgress
	/temporal/tools/cli/workflowCommands.go:371 +0x320
```

**Comment by feedmeapples** [comment]
The workflow execution continues regardless of the error, what happens is that the gRPC connection that listens to the log is getting timed out. By default it is set to 2 minutes.
Quick way to go around that is to add --context_timeout flag.

As part of this filed bug, i might add better response clarifying the --context_timeout flag, or possibly change the behavior / necessity of --context_timeout. Will keep posted

**Comment by mfateev** [comment]
@feedmeapples the _run_ command is expected to wait for the workflow completion indefinitely using long poll. The long poll is expected to return before the 2 minutes and the client should make a new call. So I'm not sure why the timeout is happening unless the context is used to stop making long poll requests.
