### ISSUE TITLE
[Bug] fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by MikePresman** [temporalio/temporal#4216]
### What are you really trying to do?
For each of my CI runs we start this temporal server as such, `temporal server start-dev --namespace ... --log-level warn`
We use this temporal server in order to run tests that we need with temporal.

### Describe the bug

This bug occurs in CircleCI, when we start all of our services one of the services we start is temporal. We use to use temporalite and experience the same problem - we thought moving to cli would help but unfortunately we still this issue from time to time.

The logs are dense and long but here they are.
```
Starting UI server...
17 Apr 2023 21:40:24.815 # Server initialized
7 Apr 2023 21:40:24.815 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
 
    ____    __
   / __/___/ /  ___
  / _// __/ _ \/ _ \
 /___/\__/_//_/\___/ v4.9.0
 High performance, minimalist Go web framework
 https://echo.labstack.com
 ____________________________________O/_______
                                     O\
17 Apr 2023 21:40:24.815 * Ready to accept connections
 ⇨ http server started on 127.0.0.1:8233
 fatal error: concurrent map read and map write
 
 goroutine 188 [running]:
 github.com/temporalio/tchannel-go/json.Register.func1({0x3385918, 0xc0007900b0}, 0xc000456840)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/json/handler.go:100 +0x4e
 github.com/temporalio/tchannel-go.HandlerFunc.Handle(0xc00012df40?, {0x3385918?, 0xc0007900b0?}, 0x470047?)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/handlers.go:49 +0x2f
 github.com/temporalio/tchannel-go.(*handlerMap).Handle(0x446a71?, {0x3385918, 0xc0007900b0}, 0xc000456840)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/handlers.go:123 +0x21c
 github.com/temporalio/tchannel-go.channelHandler.Handle({0x22b1200?}, {0x3385918, 0xc0007900b0}, 0xc000456840)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/handlers.go:131 +0x5a
 github.com/temporalio/tchannel-go.(*Connection).dispatchInbound(0xc000cceb00, 0x5f5da0?, 0xc0?, 0xc000456840, 0xc0005f5da0?)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/inbound.go:203 +0x454
 created by github.com/temporalio/tchannel-go.(*Connection).handleCallReq
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/inbound.go:125 +0xe2a
 
 goroutine 1 [select]:
 go.uber.org/fx.withTimeout({0x3382000?, 0xc00005a270}, 0xc00037f050)
 	go.uber.org/fx@v1.18.2/app.go:790 +0x165
 go.uber.org/fx.(*App).Start(0xc0005516c0, {0x3382000, 0xc00005a270})
 	go.uber.org/fx@v1.18.2/app.go:670 +0x17d
 go.temporal.io/server/temporal.ServerFx.Start(...)
 	go.temporal.io/server@v1.20.1/temporal/fx.go:280
 github.com/temporalio/cli/server.(*Server).Start(0xc00062b040)
 	github.com/temporalio/cli/server/server.go:153 +0x68
 github.com/temporalio/cli/server.NewServerCommands.func2(0xc00053cfc0)
 	github.com/temporalio/cli/server/commands.go:324 +0x18b6
 github.com/urfave/cli/v2.(*Command).Run(0xc000706f00, 0xc00053cfc0, {0xc000266b40, 0x9, 0x9})
 	github.com/urfave/cli/v2@v2.23.6/command.go:271 +0xa82
 github.com/urfave/cli/v2.(*Command).Run(0xc000707040, 0xc00053cf00, {0xc000540140, 0xa, 0xa})
 	github.com/urfave/cli/v2@v2.23.6/command.go:264 +0xcd7
 github.com/urfave/cli/v2.(*Command).Run(0xc000707b80, 0xc00062a240, {0xc0000520b0, 0xb, 0xb})
 	github.com/urfave/cli/v2@v2.23.6/command.go:264 +0xcd7
 github.com/urfave/cli/v2.(*App).RunContext(0xc00001a5a0, {0x3382000?, 0xc00005a270}, {0xc0000520b0, 0xb, 0xb})
 	github.com/urfave/cli/v2@v2.23.6/app.go:333 +0x665
 github.com/urfave/cli/v2.(*App).Run(...)
 	github.com/urfave/cli/v2@v2.23.6/app.go:310
 main.main()
 	github.com/temporalio/cli/cmd/temporal/main.go:14 +0x45
 
 goroutine 24 [select]:
 go.opencensus.io/stats/view.(*worker).start(0xc0001c4300)
 	go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0xad
 created by go.opencensus.io/stats/view.init.0
 	go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d
 
 goroutine 35 [chan receive]:
 github.com/temporalio/cli/server.NewServerCommands.func2.1()
 	github.com/temporalio/cli/server/commands.go:205 +0x85
 created by github.com/temporalio/cli/server.NewServerCommands.func2
 	github.com/temporalio/cli/server/commands.go:200 +0x2ad
 
 goroutine 36 [select]:
 database/sql.(*DB).connectionOpener(0xc000645c70, {0x3381fc8, 0xc00053d900})
 	database/sql/sql.go:1224 +0x8d
 created by database/sql.OpenDB
 	database/sql/sql.go:792 +0x18d
 
 goroutine 26 [syscall]:
 os/signal.signal_recv()
 	runtime/sigqueue.go:152 +0x2f
 os/signal.loop()
 	os/signal/signal_unix.go:23 +0x19
 created by os/signal.Notify.func1.1
 	os/signal/signal.go:151 +0x2a
 
 goroutine 50 [chan receive]:
 go.temporal.io/server/temporal.InterruptCh.func1()
 	go.temporal.io/server@v1.20.1/temporal/interrupt.go:39 +0x31
 created by go.temporal.io/server/temporal.InterruptCh
 	go.temporal.io/server@v1.20.1/temporal/interrupt.go:38 +0xea
 
 goroutine 37 [IO wait]:
 internal/poll.runtime_pollWait(0x7f61e091f058, 0x72)
 	runtime/netpoll.go:305 +0x89
 internal/poll.(*pollDesc).wait(0xc000140200?, 0x4?, 0x0)
 	internal/poll/fd_poll_runtime.go:84 +0x32
 internal/poll.(*pollDesc).waitRead(...)
 	internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Accept(0xc000140200)
 	internal/poll/fd_unix.go:614 +0x234
 net.(*netFD).accept(0xc000140200)
 	net/fd_unix.go:172 +0x35
 net.(*TCPListener).accept(0xc00040c000)
 	net/tcpsock_posix.go:142 +0x28
 net.(*TCPListener).Accept(0xc00040c000)
 	net/tcpsock.go:288 +0x3d
 net/http.(*Server).Serve(0xc00040e000, {0x3380240, 0xc00040c000})
 	net/http/server.go:3070 +0x385
 net/http.Serve(...)
 	net/http/server.go:2568
 github.com/uber-go/tally/v4/prometheus.Configuration.NewReporter.func5()
 	github.com/uber-go/tally/v4@v4.1.3/prometheus/config.go:169 +0x105
 created by github.com/uber-go/tally/v4/prometheus.Configuration.NewReporter
 	github.com/uber-go/tally/v4@v4.1.3/prometheus/config.go:155 +0x46c

	 goroutine 38 [select]:
 github.com/uber-go/tally/v4.(*scope).reportLoop(0xc000144c00, 0x0?)
 	github.com/uber-go/tally/v4@v4.1.3/scope.go:238 +0xd0
 github.com/uber-go/tally/v4.newRootScope.func1()
 	github.com/uber-go/tally/v4@v4.1.3/scope.go:180 +0x65
 created by github.com/uber-go/tally/v4.newRootScope
 	github.com/uber-go/tally/v4@v4.1.3/scope.go:178 +0x7b6
 
 goroutine 101 [select]:
 go.temporal.io/server/common/namespace.(*registry).refreshLoop(0xc00042e370, {0x3381fc8?, 0xc0005d8540})
 	go.temporal.io/server@v1.20.1/common/namespace/registry.go:353 +0x133
 go.temporal.io/server/internal/goro.(*Handle).Go.func1()
 	go.temporal.io/server@v1.20.1/internal/goro/goro.go:64 +0x6c
 created by go.temporal.io/server/internal/goro.(*Handle).Go
 	go.temporal.io/server@v1.20.1/internal/goro/goro.go:60 +0x72
 
 goroutine 52 [select]:
 google.golang.org/grpc.(*addrConn).resetTransport(0xc00094b080)
 	google.golang.org/grpc@v1.54.0/clientconn.go:1184 +0x3b8
 google.golang.org/grpc.(*addrConn).connect(0xc00094b080)
 	google.golang.org/grpc@v1.54.0/clientconn.go:819 +0x185
 created by google.golang.org/grpc.(*acBalancerWrapper).Connect
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:413 +0xbc
 
 goroutine 16 [select]:
 go.temporal.io/server/common/cluster.(*metadataImpl).refreshLoop(0xc0007056b0, {0x3381fc8, 0xc00071a800})
 	go.temporal.io/server@v1.20.1/common/cluster/metadata.go:425 +0xf8
 go.temporal.io/server/internal/goro.(*Handle).Go.func1()
 	go.temporal.io/server@v1.20.1/internal/goro/goro.go:64 +0x6c
 created by go.temporal.io/server/internal/goro.(*Handle).Go
 	go.temporal.io/server@v1.20.1/internal/goro/goro.go:60 +0x72
 
 goroutine 51 [select]:
 google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000650ac0)
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:115 +0x73
 created by google.golang.org/grpc.newCCBalancerWrapper
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:76 +0x22a
 
 goroutine 45 [IO wait]:
 internal/poll.runtime_pollWait(0x7f61e091f148, 0x72)
 	runtime/netpoll.go:305 +0x89
 internal/poll.(*pollDesc).wait(0xc0007b6200?, 0x726f6c6f63?, 0x0)
 	internal/poll/fd_poll_runtime.go:84 +0x32
 internal/poll.(*pollDesc).waitRead(...)
 	internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Accept(0xc0007b6200)
 	internal/poll/fd_unix.go:614 +0x234
 net.(*netFD).accept(0xc0007b6200)
 	net/fd_unix.go:172 +0x35
 net.(*TCPListener).accept(0xc0003d1c38)
 	net/tcpsock_posix.go:142 +0x28
 net.(*TCPListener).Accept(0xc0003d1c38)
 	net/tcpsock.go:288 +0x3d
 github.com/temporalio/tchannel-go/tnet.(*listener).Accept(0xc0001df140)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/tnet/listener.go:80 +0x77
 github.com/temporalio/tchannel-go.(*Channel).serve(0xc00015b200)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/channel.go:518 +0x46
 created by github.com/temporalio/tchannel-go.(*Channel).Serve
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/channel.go:389 +0x2fd
 
 goroutine 53 [select]:
 google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000650cc0)
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:115 +0x73
 created by google.golang.org/grpc.newCCBalancerWrapper
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:76 +0x22a
 
 goroutine 54 [select]:
 google.golang.org/grpc.(*addrConn).resetTransport(0xc00094b340)
 	google.golang.org/grpc@v1.54.0/clientconn.go:1184 +0x3b8
 google.golang.org/grpc.(*addrConn).connect(0xc00094b340)
 	google.golang.org/grpc@v1.54.0/clientconn.go:819 +0x185
 created by google.golang.org/grpc.(*acBalancerWrapper).Connect
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:413 +0xbc
 
 goroutine 15 [runnable]:
 database/sql.(*DB).conn(0xc000645c70, {0x3382070, 0xc0001f7350}, 0x1)
 	database/sql/sql.go:1341 +0x3d9
 database/sql.(*DB).exec(0xc000094a00?, {0x3382070, 0xc0001f7350}, {0x2740c7d, 0x54}, {0xc00016cce0, 0x2, 0x2}, 0xb0?)
 	database/sql/sql.go:1655 +0x5d
 database/sql.(*DB).ExecContext(0x26244e0?, {0x3382070, 0xc0001f7350}, {0x2740c7d, 0x54}, {0xc00016cce0, 0x2, 0x2})
 	database/sql/sql.go:1633 +0xe5
 go.temporal.io/server/common/persistence/sql/sqlplugin/sqlite.(*db).PruneClusterMembership(0xc0007b6800, {0x3382070, 0xc0001f7350}, 0x4d1101?)
 	go.temporal.io/server@v1.20.1/common/persistence/sql/sqlplugin/sqlite/cluster_metadata.go:266 +0xef
 go.temporal.io/server/common/persistence/sql.(*sqlClusterMetadataManager).PruneClusterMembership(0xc00008fde0, {0x3382070, 0xc0001f7350}, 0x0?)
 	go.temporal.io/server@v1.20.1/common/persistence/sql/cluster_metadata.go:242 +0xd2
 go.temporal.io/server/common/persistence.(*clusterMetadataManagerImpl).PruneClusterMembership(0x3382070?, {0x3382070?, 0xc0001f7350?}, 0x16?)
 	go.temporal.io/server@v1.20.1/common/persistence/clusterMetadataStore.go:120 +0x2c
 go.temporal.io/server/common/persistence.(*clusterMetadataRateLimitedPersistenceClient).PruneClusterMembership(0xc0001f3590, {0x3382070, 0xc0001f7350}, 0x0?)
 	go.temporal.io/server@v1.20.1/common/persistence/persistenceRateLimitedClients.go:983 +0x70
 go.temporal.io/server/common/persistence.(*clusterMetadataPersistenceClient).PruneClusterMembership(0xc0001f35c0, {0x3382070, 0xc0001f7350}, 0x0?)
 	go.temporal.io/server@v1.20.1/common/persistence/persistenceMetricClients.go:1129 +0x1eb
 go.temporal.io/server/common/persistence.(*clusterMetadataRetryablePersistenceClient).PruneClusterMembership.func1({0x3382070?, 0xc0001f7350?})
 	go.temporal.io/server@v1.20.1/common/persistence/persistenceRetryableClients.go:959 +0x3c
 go.temporal.io/server/common/backoff.ThrottleRetryContext({0x3382070, 0xc0001f7350}, 0xc000ccb4d0, {0x3366800, 0xc000153620}, 0x40f7a7?)
 	go.temporal.io/server@v1.20.1/common/backoff/retry.go:199 +0x1d7
 go.temporal.io/server/common/persistence.(*clusterMetadataRetryablePersistenceClient).PruneClusterMembership(0x0?, {0x3382070?, 0xc0001f7350?}, 0xf?)
 	go.temporal.io/server@v1.20.1/common/persistence/persistenceRetryableClients.go:962 +0x5f
 go.temporal.io/server/common/membership.(*ringpopMonitor).startHeartbeat(0xc000c1a510, {0xc00075a0a0, 0xf})
 	go.temporal.io/server@v1.20.1/common/membership/rpMonitor.go:220 +0x82
 go.temporal.io/server/common/membership.(*ringpopMonitor).Start(0x10a6d2a?)
 	go.temporal.io/server@v1.20.1/common/membership/rpMonitor.go:133 +0x250
 go.temporal.io/server/common/resource.MembershipMonitorProvider.func1({0x2200600, 0x33674c0})
 	go.temporal.io/server@v1.20.1/common/resource/fx.go:287 +0x22
 go.uber.org/fx/internal/lifecycle.(*Lifecycle).runStartHook(0xc000705810, {0x3382038, 0xc00064d6e0}, {0xc000013638, 0xc0001df560, {{0xc000bfc2c0, 0x3f}, {0x39becac, 0x33}, 0x11c}})
 	go.uber.org/fx@v1.18.2/internal/lifecycle/lifecycle.go:130 +0x208
 go.uber.org/fx/internal/lifecycle.(*Lifecycle).Start(0xc000705810, {0x3382038, 0xc00064d6e0})
 	go.uber.org/fx@v1.18.2/internal/lifecycle/lifecycle.go:95 +0x30e
 go.uber.org/fx.(*App).start(0xc000bd4c30, {0x3382038, 0xc00064d6e0})
 	go.uber.org/fx@v1.18.2/app.go:679 +0x36
 go.uber.org/fx.withTimeout.func1()
 	go.uber.org/fx@v1.18.2/app.go:784 +0x85
 created by go.uber.org/fx.withTimeout
 	go.uber.org/fx@v1.18.2/app.go:772 +0xec
 
 goroutine 14 [select]:
 google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0007780a0, 0x1)
 	google.golang.org/grpc@v1.54.0/internal/transport/controlbuf.go:417 +0x115
 google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000194070)
 	google.golang.org/grpc@v1.54.0/internal/transport/controlbuf.go:549 +0x91
 google.golang.org/grpc/internal/transport.newHTTP2Client.func6()
 	google.golang.org/grpc@v1.54.0/internal/transport/http2_client.go:448 +0x7b
 created by google.golang.org/grpc/internal/transport.newHTTP2Client
 	google.golang.org/grpc@v1.54.0/internal/transport/http2_client.go:446 +0x2293
 
 goroutine 68 [IO wait]:
 internal/poll.runtime_pollWait(0x7f61e091f328, 0x72)
 	runtime/netpoll.go:305 +0x89
 internal/poll.(*pollDesc).wait(0xc000140a80?, 0x6?, 0x0)
 	internal/poll/fd_poll_runtime.go:84 +0x32
 internal/poll.(*pollDesc).waitRead(...)
 	internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Accept(0xc000140a80)
 	internal/poll/fd_unix.go:614 +0x234
 net.(*netFD).accept(0xc000140a80)
 	net/fd_unix.go:172 +0x35
 net.(*TCPListener).accept(0xc0007f4150)
 	net/tcpsock_posix.go:142 +0x28
 net.(*TCPListener).Accept(0xc0007f4150)
 	net/tcpsock.go:288 +0x3d
 github.com/temporalio/tchannel-go/tnet.(*listener).Accept(0xc0007dc2a0)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/tnet/listener.go:80 +0x77
 github.com/temporalio/tchannel-go.(*Channel).serve(0xc00066e800)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/channel.go:518 +0x46
 created by github.com/temporalio/tchannel-go.(*Channel).Serve
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/channel.go:389 +0x2fd
 
 goroutine 69 [select]:
 google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00071a0c0)
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:115 +0x73
 created by google.golang.org/grpc.newCCBalancerWrapper
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:76 +0x22a
 
 goroutine 70 [select]:
 google.golang.org/grpc.(*addrConn).resetTransport(0xc0005ac2c0)
 	google.golang.org/grpc@v1.54.0/clientconn.go:1184 +0x3b8
 google.golang.org/grpc.(*addrConn).connect(0xc0005ac2c0)
 	google.golang.org/grpc@v1.54.0/clientconn.go:819 +0x185
 created by google.golang.org/grpc.(*acBalancerWrapper).Connect
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:413 +0xbc
 
 goroutine 71 [select]:
 google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00071a280)
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:115 +0x73
 created by google.golang.org/grpc.newCCBalancerWrapper
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:76 +0x22a
 
 goroutine 72 [select]:
 google.golang.org/grpc.(*addrConn).resetTransport(0xc0005ac580)
 	google.golang.org/grpc@v1.54.0/clientconn.go:1184 +0x3b8
 google.golang.org/grpc.(*addrConn).connect(0xc0005ac580)
 	google.golang.org/grpc@v1.54.0/clientconn.go:819 +0x185
 created by google.golang.org/grpc.(*acBalancerWrapper).Connect
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:413 +0xbc
 
 goroutine 13 [IO wait]:
 internal/poll.runtime_pollWait(0x7f61e091ed88, 0x72)
 	runtime/netpoll.go:305 +0x89
 internal/poll.(*pollDesc).wait(0xc000140400?, 0xc000c9a000?, 0x0)
 	internal/poll/fd_poll_runtime.go:84 +0x32
 internal/poll.(*pollDesc).waitRead(...)
 	internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Read(0xc000140400, {0xc000c9a000, 0x8000, 0x8000})
 	internal/poll/fd_unix.go:167 +0x25a
 net.(*netFD).Read(0xc000140400, {0xc000c9a000?, 0x0?, 0x0?})
 	net/fd_posix.go:55 +0x29
 net.(*conn).Read(0xc000014028, {0xc000c9a000?, 0xc0003591a0?, 0x0?})
 	net/net.go:183 +0x45
 bufio.(*Reader).Read(0xc0005f4120, {0xc000cb2040, 0x9, 0xe?})
 	bufio/bufio.go:237 +0x1bb
 io.ReadAtLeast({0x3363440, 0xc0005f4120}, {0xc000cb2040, 0x9, 0x9}, 0x9)
 	io/io.go:332 +0x9a
 io.ReadFull(...)
 	io/io.go:351
 golang.org/x/net/http2.readFrameHeader({0xc000cb2040?, 0x9?, 0x0?}, {0x3363440?, 0xc0005f4120?})
 	golang.org/x/net@v0.8.0/http2/frame.go:237 +0x6e
 golang.org/x/net/http2.(*Framer).ReadFrame(0xc000cb2000)
 	golang.org/x/net@v0.8.0/http2/frame.go:498 +0x95
 google.golang.org/grpc/internal/transport.(*http2Client).readServerPreface(0xc000cb6000)
 	google.golang.org/grpc@v1.54.0/internal/transport/http2_client.go:1562 +0x45
 google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc000cb6000, 0xc00094b8c0?)
 	google.golang.org/grpc@v1.54.0/internal/transport/http2_client.go:1580 +0x8e
 created by google.golang.org/grpc/internal/transport.newHTTP2Client
 	google.golang.org/grpc@v1.54.0/internal/transport/http2_client.go:394 +0x1c3b
 
 goroutine 12 [chan receive]:
 google.golang.org/grpc/internal/transport.newHTTP2Client.func4({0x338de48, 0xc000014028})
 	google.golang.org/grpc@v1.54.0/internal/transport/http2_client.go:243 +0x8d
 created by google.golang.org/grpc/internal/transport.newHTTP2Client
 	google.golang.org/grpc@v1.54.0/internal/transport/http2_client.go:241 +0x71e
 
 goroutine 75 [IO wait]:
 internal/poll.runtime_pollWait(0x7f61e091f508, 0x72)
 	runtime/netpoll.go:305 +0x89
 internal/poll.(*pollDesc).wait(0xc0001c4500?, 0x6?, 0x0)
 	internal/poll/fd_poll_runtime.go:84 +0x32
 internal/poll.(*pollDesc).waitRead(...)
 	internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Accept(0xc0001c4500)
 	internal/poll/fd_unix.go:614 +0x234
 net.(*netFD).accept(0xc0001c4500)
 	net/fd_unix.go:172 +0x35
 net.(*TCPListener).accept(0xc00040c420)
 	net/tcpsock_posix.go:142 +0x28
 net.(*TCPListener).Accept(0xc00040c420)
 	net/tcpsock.go:288 +0x3d
 github.com/temporalio/tchannel-go/tnet.(*listener).Accept(0xc00012ccc0)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/tnet/listener.go:80 +0x77
 github.com/temporalio/tchannel-go.(*Channel).serve(0xc0000fd400)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/channel.go:518 +0x46
 created by github.com/temporalio/tchannel-go.(*Channel).Serve
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/channel.go:389 +0x2fd
 
 goroutine 76 [select]:
 google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000745980)
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:115 +0x73
 created by google.golang.org/grpc.newCCBalancerWrapper
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:76 +0x22a
 
 goroutine 77 [select]:
 google.golang.org/grpc.(*addrConn).resetTransport(0xc0008162c0)
 	google.golang.org/grpc@v1.54.0/clientconn.go:1184 +0x3b8
 google.golang.org/grpc.(*addrConn).connect(0xc0008162c0)
 	google.golang.org/grpc@v1.54.0/clientconn.go:819 +0x185
 created by google.golang.org/grpc.(*acBalancerWrapper).Connect
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:413 +0xbc
 
 goroutine 78 [select]:
 google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000745ac0)
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:115 +0x73
 created by google.golang.org/grpc.newCCBalancerWrapper
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:76 +0x22a
 
 goroutine 79 [select]:
 google.golang.org/grpc.(*addrConn).resetTransport(0xc000816580)
 	google.golang.org/grpc@v1.54.0/clientconn.go:1184 +0x3b8
 google.golang.org/grpc.(*addrConn).connect(0xc000816580)
 	google.golang.org/grpc@v1.54.0/clientconn.go:819 +0x185
 created by google.golang.org/grpc.(*acBalancerWrapper).Connect
 	google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:413 +0xbc
 
 goroutine 56 [chan receive]:
 google.golang.org/grpc/internal/transport.newHTTP2Client.func4({0x338de48, 0xc00065c000})
 	google.golang.org/grpc@v1.54.0/internal/transport/http2_client.go:243 +0x8d
 created by google.golang.org/grpc/internal/transport.newHTTP2Client
 	google.golang.org/grpc@v1.54.0/internal/transport/http2_client.go:241 +0x71e
 
 goroutine 33 [IO wait]:
 internal/poll.runtime_pollWait(0x7f61e091f6e8, 0x72)
 	runtime/netpoll.go:305 +0x89
 internal/poll.(*pollDesc).wait(0xc000652d00?, 0x0?, 0x0)
 	internal/poll/fd_poll_runtime.go:84 +0x32
 internal/poll.(*pollDesc).waitRead(...)
 	internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Accept(0xc000652d00)
 	internal/poll/fd_unix.go:614 +0x234
 net.(*netFD).accept(0xc000652d00)
 	net/fd_unix.go:172 +0x35
 net.(*TCPListener).accept(0xc0000135a8)
 	net/tcpsock_posix.go:142 +0x28
 net.(*TCPListener).Accept(0xc0000135a8)
 	net/tcpsock.go:288 +0x3d
 github.com/temporalio/tchannel-go/tnet.(*listener).Accept(0xc0001df320)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/tnet/listener.go:80 +0x77
 github.com/temporalio/tchannel-go.(*Channel).serve(0xc0000fd000)
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/channel.go:518 +0x46
 created by github.com/temporalio/tchannel-go.(*Channel).Serve
 	github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/channel.go:389 +0x2fd
```

### Minimal Reproduction
1. Run temporal cli on CircleCI as such `temporal server start-dev --namespace ABC --log-level warn`
2. Occasionally (not all the time) you may see the same error.

### Environment/Versions

- OS and processor: Linux
- Temporal Version: v0.8.0
- Are you using Docker or Kubernetes or building Temporal from source?
Building from source.

**Comment by mindaugasrukas** [comment]
Duplicate: #4000
