### ISSUE TITLE
Sending signal using batch request gives error in workflow

### ISSUE THREAD

**Issue by akashsax14** [temporalio/temporal#4373]
Issue
===
We are using typescript sdk to send a signal (with args) to a list of workflows using batch operation. The worker is setup with the default data convertor/default settings. When the signal is received by the workflow we get an error. 

### Error
```
{
  "message": "Unknown encoding: binary/protobuf",
  "source": "TypeScriptSDK",
  "stackTrace": "/app/workflow-bundle-5feb3d484fc78c2a5e62.js:4067\n            throw new errors_1.ValueError(`Unknown encoding: ${encoding}`);\n            ^\n\nValueError: Unknown encoding: binary/protobuf\n    at DefaultPayloadConverter.fromPayload (/app/node_modules/@temporalio/common/src/converter/payload-converter.ts:163:12)\n    at /app/node_modules/@temporalio/common/src/converter/payload-converter.ts:84:54\n    at Array.map (<anonymous>)\n    at arrayFromPayloads (/app/node_modules/@temporalio/common/src/converter/payload-converter.ts:84:18)\n    at Activator.signalWorkflow (/app/node_modules/@temporalio/workflow/src/internals.ts:545:30)\n    at /app/node_modules/@temporalio/workflow/src/worker-interface.ts:215:29\n    at Object.activate (/app/node_modules/@temporalio/workflow/src/worker-interface.ts:221:2)\n    at evalmachine.<anonymous>:1:18",
  "encodedAttributes": null,
  "cause": null
}
```

### Stack Trace
```
/app/workflow-bundle-5feb3d484fc78c2a5e62.js:4067
            throw new errors_1.ValueError(Unknown encoding: ${encoding});
            ^
ValueError: Unknown encoding: binary/protobuf
    at DefaultPayloadConverter.fromPayload (/app/node_modules/@temporalio/common/src/converter/payload-converter.ts:163:12)
    at /app/node_modules/@temporalio/common/src/converter/payload-converter.ts:84:54
    at Array.map (<anonymous>)
    at arrayFromPayloads (/app/node_modules/@temporalio/common/src/converter/payload-converter.ts:84:18)
    at Activator.signalWorkflow (/app/node_modules/@temporalio/workflow/src/internals.ts:545:30)
    at /app/node_modules/@temporalio/workflow/src/worker-interface.ts:215:29
    at Object.activate (/app/node_modules/@temporalio/workflow/src/worker-interface.ts:221:2)
    at evalmachine.<anonymous>:1:18
```

### Sample signal args received by workflow
```
[
  {
    "metadata": {
      "encoding": "YmluYXJ5L3Byb3RvYnVm",
      "messageType": "dGVtcG9yYWwuYXBpLmNvbW1vbi52MS5QYXlsb2Fkcw==",
      "encodingDecoded": "binary/protobuf"
    },
    "data": "ChwKFgoIZW5jb2RpbmcSCmpzb24vcGxhaW4SAnt9"
  }
]
```

### Batch Request

```
export async function sendSignals(
  temporalClient: WorkflowClient,
  temporalWorkflowIds: string[],
  signalDef: string,
  args: any,
  reason: string,
) {
  const batchOperationRequest: temporal.api.workflowservice.v1.IStartBatchOperationRequest = {
    namespace: TEMPORAL_NAMESPACE,
    jobId: randomUUID(),
    reason,
    signalOperation: {
      input: {
        payloads: [{ etag: args["etag"], isDefault: args["isDefault"] }].map((arg) =>
          temporalClient.options.loadedDataConverter.payloadConverter.toPayload(arg),
        ),
      },
      signal: signalDef,
    },
    executions: temporalWorkflowIds.map((id) => ({ workflowId: id })),
  };
  await temporalClient.workflowService.startBatchOperation(batchOperationRequest);
}
```

Expected
======
That the signal args should be correctly received by the workflow when sending a signal using batch operation.

**Comment by mjameswh** [comment]
**Extra notes**

This error happens using _raw gRPC calls_ (there is no high level client API for this in any SDK). I confirmed that the structure of the protobuf request sent to the server is correct, but the server seems to reencode the signal input's payloads.
