### ISSUE TITLE
nil internalTask pointer returned by matchingEngine.getTask in CI

### ISSUE THREAD

**Issue by tdeebswihart** [temporalio/temporal#4892]
## Expected Behavior
`matchingEngine.getTask` returns **either** a non-nil `internalTask` pointer or non-nil error error.

## Actual Behavior

`matchingEngine.getTask` returned both a nil error and a nil `internalTask`
[It fails after dereferencing a nil pointer](https://buildkite.com/temporal/temporal-public/builds/12245#018acd1f-f44c-4807-baa2-313199195999):
```
FAIL: TestMatchingEngineSuite (15.84s)
--
  | --- FAIL: TestMatchingEngineSuite/TestAddTaskAfterStartFailure (0.10s)
  | matching_engine_test.go:1707:
  | Error Trace:	/temporal/service/matching/matching_engine_test.go:1707
  | Error:      	Received unexpected error:
  | no tasks
  | Test:       	TestMatchingEngineSuite/TestAddTaskAfterStartFailure
  | suite.go:87: test panicked: runtime error: invalid memory address or nil pointer dereference
--
  | goroutine 210 [running]:
  | runtime/debug.Stack()
  | /usr/local/go/src/runtime/debug/stack.go:24 +0x67
  | github.com/stretchr/testify/suite.failOnPanic(0xc000412340, {0x2fe8200, 0x585beb0})
  | /go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:87 +0x3a
  | github.com/stretchr/testify/suite.Run.func1.1()
  | /go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:183 +0x345
  | panic({0x2fe8200?, 0x585beb0?})
  | /usr/local/go/src/runtime/panic.go:920 +0x270
  | go.temporal.io/server/service/matching.(*internalTask).finish(0x0, {0x4599160, 0xc0003640a0})
  | /temporal/service/matching/task.go:164 +0x75
  | go.temporal.io/server/service/matching.(*matchingEngineSuite).TestAddTaskAfterStartFailure(0xc000884120)
  | /temporal/service/matching/matching_engine_test.go:1709 +0x594
  | reflect.Value.call({0xc0009da240?, 0xc00030c1b0?, 0x44593a?}, {0x3346a3d, 0x4}, {0xc00070dda8, 0x1, 0xc00070dbc8?})
  | /usr/local/go/src/reflect/value.go:596 +0x14a5
  | reflect.Value.Call({0xc0009da240?, 0xc00030c1b0?, 0xc000884120?}, {0xc00070dda8, 0x1, 0x1})
  | /usr/local/go/src/reflect/value.go:380 +0xb6
  | github.com/stretchr/testify/suite.Run.func1(0xc000412340)
  | /go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:197 +0x685
  | testing.tRunner(0xc000412340, 0xc0008842d0)
  | /usr/local/go/src/testing/testing.go:1595 +0x239
  | created by testing.(*T).Run in goroutine 199
  | /usr/local/go/src/testing/testing.go:1648 +0x82b
```

## Steps to Reproduce the Problem

This occurred in buildkite but not when running unit-tests locally

## Specifications

  - Version:
  - Platform:

**Comment by dnr** [comment]
It is returning a non-nil error there. It's just a flaky test. Fixed by #4989
