### ISSUE TITLE
Can't display archived workflows which have past the retention

### ISSUE THREAD

**Issue by Aoao54** [temporalio/temporal#5022]
I put this also on Slack : https://temporalio.slack.com/archives/CTRCR8RBP/p1697683052222109
## Expected Behavior
Display archived workflows which have past the retention from archived file store S3.

## Actual Behavior
Can't display it both in web-ui or tctl 

![image](https://github.com/temporalio/temporal/assets/84021683/bc01d620-1964-493a-8b96-6ed13e9c70b1)

`➜  ~ tctl wf desc -w    hello_world_workflowID -r d07eaf4b-83d4-4bf6-b387-a3ae1caf584c                                    
Error: Describe workflow execution failed
Error Details: rpc error: code = NotFound desc = Workflow executionsRow not found.  WorkflowId: hello_world_workflowID, RunId: d07eaf4b-83d4-4bf6-b387-a3ae1caf584c
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x1c
github.com/temporalio/tctl/cli_curr.printError({0x101f76e2c, 0x22}, {0x1026cd0e0, 0x140001262c0})
	github.com/temporalio/tctl/cli_curr/util.go:393 +0x1c0
github.com/temporalio/tctl/cli_curr.ErrorAndExit({0x101f76e2c?, 0x1026dd3a8?}, {0x1026cd0e0?, 0x140001262c0?})
	github.com/temporalio/tctl/cli_curr/util.go:404 +0x28
github.com/temporalio/tctl/cli_curr.describeWorkflowHelper(0x140000c0c60, {0x16efa77e8, 0x16}, {0x16efa7802, 0x24})
	github.com/temporalio/tctl/cli_curr/workflowCommands.go:905 +0x1f4
github.com/temporalio/tctl/cli_curr.DescribeWorkflow(0x140000c0c60)
	github.com/temporalio/tctl/cli_curr/workflowCommands.go:870 +0x68
github.com/temporalio/tctl/cli_curr.newWorkflowCommands.func15(0x140000a6640?)
	github.com/temporalio/tctl/cli_curr/workflow.go:237 +0x1c
github.com/urfave/cli.HandleAction({0x10241d620?, 0x1026c2060?}, 0x8?)
	github.com/urfave/cli@v1.22.10/app.go:526 +0x94
github.com/urfave/cli.Command.Run({{0x101f38abc, 0x8}, {0x0, 0x0}, {0x1400018b150, 0x1, 0x1}, {0x101f8357d, 0x26}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.10/command.go:173 +0x504
github.com/urfave/cli.(*App).RunAsSubcommand(0x1400055d340, 0x140000c09a0)
	github.com/urfave/cli@v1.22.10/app.go:405 +0xa68
github.com/urfave/cli.Command.startApp({{0x101f395cc, 0x8}, {0x0, 0x0}, {0x1400018b720, 0x1, 0x1}, {0x101f5f7be, 0x19}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.10/command.go:378 +0x9c4
github.com/urfave/cli.Command.Run({{0x101f395cc, 0x8}, {0x0, 0x0}, {0x1400018b720, 0x1, 0x1}, {0x101f5f7be, 0x19}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.10/command.go:102 +0x650
github.com/urfave/cli.(*App).Run(0x1400055cfc0, {0x140001a6000, 0x7, 0x7})
	github.com/urfave/cli@v1.22.10/app.go:277 +0x7e4
main.main()
	./main.go:47 +0xc0`
## Steps to Reproduce the Problem

  1. Set up a local S3-server and local temporal-server with this archival config 
 

> archival:
>   history:
>     state: "enabled"
>     enableRead: true
>     provider:
>       s3store:
>         region: "us-east-1"
>         endpoint: "http://127.0.0.1:4566/"
>         s3ForcePathStyle: true
>   visibility:
>     state: "enabled"
>     enableRead: true
>     provider:
>       s3store:
>         region: "us-east-1"
>         endpoint: "http://127.0.0.1:4566/"
>         s3ForcePathStyle: true
> 
> namespaceDefaults:
>   archival:
>     history:
>       state: "enabled"
>       URI: "s3://temporal-development"
>     visibility:
>       state: "enabled"
>       URI: "s3://temporal-development"

  2. set a default namespace which the retention-period is 1h
> temporal operator namespace create --retention=1h default
  3. run some easy sample-go workflows. When the archived workflows past the retention, you can't open it from web-ui or describe it use tclt cmd.
> tctl wf desc -w    hello_world_workflowID -r d07eaf4b-83d4-4bf6-b387-a3ae1caf584c       

## Specifications

  - Version: 
    temporal-server: 1.22
    ui-server:  2.19.0
  - Platform: S3, MAC

**Comment by yycptt** [comment]
Describe workflow execution does not support archived workflows.

History for archived workflows can be retrieved from archival storage and returned via the GetWorkflowExecutionHistory API or `tctl wf show` when runID is specified.

**Comment by fabioyy** [comment]
same here. I can get the workflow by using cli, but cannot get in the web ( passing workflow and run_id ) on the url.
strange that it was ok in the past. I redeployed my k8 cluster and reinstall the helm. ( a little older version ).
