### ISSUE TITLE
[Bug] Race: Concurrent map read/write, probably in server

### ISSUE THREAD

**Issue by josh-berry** [temporalio/temporal#5123]
Tests against the CLI with server v1.22.2 (not yet merged) [failed](https://github.com/temporalio/cli/actions/runs/6867519478/job/18676041242?pr=385) with a concurrent map read/write panic.

Offending goroutines appear to be:

```

goroutine 57 [runnable]:
github.com/temporalio/tchannel-go/json.Register({0x1b14874f778?, 0xc000460310}, 0x32c58a3?, 0xc000164fb0)
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/json/handler.go:119 +0x1f2
github.com/temporalio/ringpop-go/swim.(*Node).registerHandlers(0xc00128a1a0)
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/ringpop-go@v0.0.0-20230606200434-b5c079f412d3/swim/handlers.go:81 +0x879
github.com/temporalio/ringpop-go/swim.NewNode({0xc00044fa40, 0x2d}, {0xc000a06160, 0xf}, {0x3c463e8?, 0xc000460310}, 0x0?)
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/ringpop-go@v0.0.0-20230606200434-b5c079f412d3/swim/node.go:278 +0x7b4
github.com/temporalio/ringpop-go.(*Ringpop).init(0xc0009b0420)
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/ringpop-go@v0.0.0-20230606200434-b5c079f412d3/ringpop.go:195 +0x2cc
github.com/temporalio/ringpop-go.(*Ringpop).Bootstrap(0xc0009b0420, 0xdf69f0?)
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/ringpop-go@v0.0.0-20230606200434-b5c079f412d3/ringpop.go:419 +0x3d
go.temporal.io/server/common/membership/ringpop.(*service).bootstrap.func1()
	C:/Users/runneradmin/go/pkg/mod/go.temporal.io/server@v1.22.2/common/membership/ringpop/ringpop.go:108 +0x105
go.temporal.io/server/common/backoff.ThrottleRetry.func1({0x3, 0xd0bf000000000000})
	C:/Users/runneradmin/go/pkg/mod/go.temporal.io/server@v1.22.2/common/backoff/retry.go:119 +0x1b
go.temporal.io/server/common/backoff.ThrottleRetryContext({0x3c3ea80, 0xc000054220}, 0xc000ca5300, {0x3c205c0, 0xc0005e4270}, 0x28?)
	C:/Users/runneradmin/go/pkg/mod/go.temporal.io/server@v1.22.2/common/backoff/retry.go:145 +0x20a
go.temporal.io/server/common/backoff.ThrottleRetry(0x0?, {0x3c205c0?, 0xc0005e4270?}, 0x4?)
	C:/Users/runneradmin/go/pkg/mod/go.temporal.io/server@v1.22.2/common/backoff/retry.go:120 +0x59
go.temporal.io/server/common/membership/ringpop.(*service).bootstrap(0xc000aaaae0, 0xc000ca94f8, 0x2540be400)
	C:/Users/runneradmin/go/pkg/mod/go.temporal.io/server@v1.22.2/common/membership/ringpop/ringpop.go:114 +0xee
go.temporal.io/server/common/membership/ringpop.(*service).start(...)
	C:/Users/runneradmin/go/pkg/mod/go.temporal.io/server@v1.22.2/common/membership/ringpop/ringpop.go:84
go.temporal.io/server/common/membership/ringpop.(*monitor).Start(0xc000aa9b00?)
	C:/Users/runneradmin/go/pkg/mod/go.temporal.io/server@v1.22.2/common/membership/ringpop/monitor.go:139 +0x465
go.temporal.io/server/service/worker.(*Service).Start(0xc0009b2780)
	C:/Users/runneradmin/go/pkg/mod/go.temporal.io/server@v1.22.2/service/worker/service.go:393 +0x1a4
go.uber.org/fx/internal/lifecycle.Wrap[...].func1()
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/fx@v1.20.0/internal/lifecycle/lifecycle.go:80 +0x1b
go.uber.org/fx/internal/lifecycle.(*Lifecycle).runStartHook(0xc0008edce0, {0x3c3eab8, 0xc00080d500}, {0xc00082bcb0, 0xc00082bcc8, {0xc000a79940, 0x3a}, {0xc000a79a00, 0x39}, {{0xc000a79ac0, ...}, ...}})
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/fx@v1.20.0/internal/lifecycle/lifecycle.go:256 +0x212
go.uber.org/fx/internal/lifecycle.(*Lifecycle).Start(0xc0008edce0, {0x3c3eab8, 0xc00080d500})
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/fx@v1.20.0/internal/lifecycle/lifecycle.go:216 +0x4c8
go.uber.org/fx.(*App).start.func1({0x3c3eab8, 0xc00080d500})
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/fx@v1.20.0/app.go:679 +0x3c
go.uber.org/fx.(*App).withRollback(0xc0001e84b0, {0x3c3eab8, 0xc00080d500}, 0xc000281740?)
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/fx@v1.20.0/app.go:661 +0x38
go.uber.org/fx.(*App).start(0xc000941328?, {0x3c3eab8?, 0xc00080d500?})
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/fx@v1.20.0/app.go:678 +0x3f
go.uber.org/fx.withTimeout.func1()
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/fx@v1.20.0/app.go:782 +0x85
created by go.uber.org/fx.withTimeout
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/fx@v1.20.0/app.go:770 +0xea
```

and

```
 fatal error: concurrent map read and map write

goroutine 773 [running]:
github.com/temporalio/tchannel-go/json.Register.func1({0x3c42788, 0xc000943530}, 0xc000a0d440)
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/json/handler.go:100 +0x4e
github.com/temporalio/tchannel-go.HandlerFunc.Handle(0xc000837b00?, {0x3c42788?, 0xc000943530?}, 0xe50dc7?)
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/handlers.go:49 +0x2f
github.com/temporalio/tchannel-go.(*handlerMap).Handle(0xe26e71?, {0x3c42788, 0xc000943530}, 0xc000a0d440)
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/handlers.go:123 +0x21c
github.com/temporalio/tchannel-go.channelHandler.Handle({0x2ea2a00?}, {0x3c42788, 0xc000943530}, 0xc000a0d440)
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/handlers.go:131 +0x5a
github.com/temporalio/tchannel-go.(*Connection).dispatchInbound(0xc001230000, 0x0?, 0x0?, 0xc000a0d440, 0x0?)
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/inbound.go:203 +0x454
created by github.com/temporalio/tchannel-go.(*Connection).handleCallReq
	C:/Users/runneradmin/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/inbound.go:125 +0xe2a
```

This particular map appears to only be accessible from tchannel-go's `json.Register` and friends. Looking more into why but wanted to open this issue to track/log findings. (It's probably a server issue, but I'm opening it in CLI for now since that's where the issue was first seen. Will move once I'm sure it's actually a server problem.)

**Comment by tdeebswihart** [comment]
I wonder if this is related to #5055...
