### ISSUE TITLE
deleted schedule showing

### ISSUE THREAD

**Issue by jesse-triplewhale** [temporalio/temporal#5785]
version: 1.22.4
self-hosted

I deleted a schedule in the UI, but it is still returning in the web UI and via
```
$ temporal schedule list
  ScheduleId    WorkflowType   Paused  Notes  NextRunTime  LastRunTime  
...
```

When I try to delete
```
$ temporal schedule delete ...
Error: unable to delete schedule: workflow execution already completed
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.11/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.20.11/x64/src/runtime/debug/stack.go:16 +0x19
github.com/temporalio/cli/app.HandleError(0x24d5b60?, {0x320df40, 0xc00065a2e0})
        /home/runner/work/cli/cli/app/app.go:73 +0x15b
github.com/urfave/cli/v2.(*App).handleExitCoder(0xc0008fe160?, 0xc000225400?, {0x320df40?, 0xc00065a2e0?})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:452 +0x38
github.com/urfave/cli/v2.(*Command).Run(0xc0008fe160, 0xc000699bc0, {0xc0000af770, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:276 +0xa18
github.com/urfave/cli/v2.(*Command).Run(0x4744c20, 0xc000699a80, {0xc0000a5aa0, 0x6, 0x6})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*Command).Run(0xc000900c60, 0xc000699940, {0xc000050070, 0x7, 0x7})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc0007b25a0, {0x322f340?, 0xc00005a028}, {0xc000050070, 0x7, 0x7})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(0x60?, {0xc000050070?, 0x0?, 0x0?})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309 +0x38
main.main()
        /home/runner/work/cli/cli/cmd/temporal/main.go:14 +0x33
```

Thank you!

**Comment by dnr** [comment]
That looks like the change to the status of the schedule workflow hasn't made it to visibility. Which main and visibility backends are you using? Have you noticed any other visibility issues, any other situations where the result of ListWorkflows isn't in sync with the status of running workflows? Any visibility-related errors in logs or metrics, i.e. for visibility task processing or ES bulk processor (if using ES)?

**Comment by jesse-triplewhale** [comment]
Hi, thanks for the response - we're using postgres + Elasticsearch. I haven't noticed any other behaviors like this (although I think I have seen this behavior multiple times). I ended up deleting and recreating the namespace to clean it up
