### ISSUE TITLE
Panic When Upgrading From 1.20.4 To 1.21.6

### ISSUE THREAD

**Issue by ytaben** [temporalio/temporal#6307]
## Expected Behavior
History pods operate normally when redeployed from 1.20.4 to 1.21.6

## Actual Behavior
History pods panic with the following trace:
```
main.PanicErrorWrapper
panic: unable to find queue category by queye category ID: 5

goroutine 3960 [running]:
go.temporal.io/server/service/history/shard.loadShardInfoCompatibilityCheckWithoutReplication(0xc000f40500)
	/go/pkg/mod/go.temporal.io/server@v1.21.6/service/history/shard/compatibility.go:65 +0x334
go.temporal.io/server/service/history/shard.loadShardInfoCompatibilityCheck({0x304b310, 0xc00098a210}, 0xc001f6a810?)
	/go/pkg/mod/go.temporal.io/server@v1.21.6/service/history/shard/compatibility.go:47 +0x3f
go.temporal.io/server/service/history/shard.(*ContextImpl).loadShardMetadata(0xc000423680, 0xc001f7be7f)
	/go/pkg/mod/go.temporal.io/server@v1.21.6/service/history/shard/context_impl.go:1670 +0x1e9
go.temporal.io/server/service/history/shard.(*ContextImpl).acquireShard.func1()
	/go/pkg/mod/go.temporal.io/server@v1.21.6/service/history/shard/context_impl.go:1821 +0x46
go.temporal.io/server/common/backoff.ThrottleRetry.func1({0xc001c9bcf8, 0x40594a})
	/go/pkg/mod/go.temporal.io/server@v1.21.6/common/backoff/retry.go:119 +0x1b
go.temporal.io/server/common/backoff.ThrottleRetryContext({0x3035c20, 0xc00013c000}, 0xc001f7be28, {0x3015760, 0xc00052e630}, 0x28?)
	/go/pkg/mod/go.temporal.io/server@v1.21.6/common/backoff/retry.go:145 +0x20a
go.temporal.io/server/common/backoff.ThrottleRetry(0x0?, {0x3015760?, 0xc00052e630?}, 0x3?)
	/go/pkg/mod/go.temporal.io/server@v1.21.6/common/backoff/retry.go:120 +0x59
go.temporal.io/server/service/history/shard.(*ContextImpl).acquireShard(0xc000423680)
	/go/pkg/mod/go.temporal.io/server@v1.21.6/service/history/shard/context_impl.go:1889 +0x106
created by go.temporal.io/server/service/history/shard.(*ContextImpl).transition.func1
	/go/pkg/mod/go.temporal.io/server@v1.21.6/service/history/shard/context_impl.go:1483 +0x11a
panic: unable to find queue category by queye category ID: 5
```

## Steps to Reproduce the Problem

  1. Run Temporal cluster version 1.20.4 with archival enabled
  1. Disable archival globally in the static config
  1. Attempt to upgrade to 1.21.6

## Specifications

  - Version: 1.20.4\1.21.6
  - Platform: Linux amd64

## Additional Info:
The code that panics was introduced in [this PR](https://github.com/temporalio/temporal/pull/4190) (CC @wxing1292 )

We are not entirely sure how Temporal stores stuff in the persistence layer (a lot of it is blobs) but there appear to be shards with  archival queues while archival is actually disabled.

Given this server version is old and the code that bugs out appears to be migrationary in nature - we are ok with a workaround just for the upgrade but we wanted to make sure that whatever we do is safe.

Specifically - if we were to enable archival globally (but not for any namespace in particular), perform the upgrade and then again disable archival again - would we face any future issues?
Alternatively - should we hack the code to load the archival category for the compatibility code to work? (it appears to be loaded conditionally on archival being enabled cluster wide)

We were looking for a way to do the upgrade without archival since we disabled it because it has previously caused a different panic (patched in a newer version of Temporal we're not on yet)

Happy to provide additional info or help with the investigation in any way.
Thank you!

**Comment by wxing1292** [comment]
i believe the 1.21.x version does not take workflow archival into considersation and caused this issue. 
the bug should be fixed by 1.22.x? cc @yycptt
i will let oss server team to take over this conversation 

[1.21.x logic](https://github.com/temporalio/temporal/blame/v1.21.6/service/history/shard/context_impl.go#L1670)
[1.22.x logic](https://github.com/temporalio/temporal/blame/v1.22.7/service/history/shard/context_impl.go#L1670)

**Comment by ytaben** [comment]
Hey @wxing1292 @yycptt,

Any chance you were able to take a look?
You mentioned that the bug is allegedly fixed in 1.22.x but unless it's safe to jump to 1.22.x (which I assume it isn't) - we need a safe way to upgrade to 1.21.x

We would be happy to help with the investigation and\or make a fix contribution, we just aren't familiar enough with the codebase and shard structure to be certain our fix works and we don't introduce another regression

**Comment by yycptt** [comment]
One way I can think of is 
- Set `history.archivalProcessorSchedulerWorkerCount` dynamic config to 0 (this will prevent any archival task from being executed). You can also set `history.queuePendingTasksMaxCount` to a lower value like 1000 to prevent loading too many tasks into memory as there's no worker to process them.
- Enable archival in the static config (this will register the queue category so shard context logic won't panic). 
- Deploy 1.21, and then 1.22. 
- Revert both config changes and restart the service

If you don't care about archival task is executed or not, I guess just enabled the static config for archival, do the upgrade for 1.21 and 1.22 and then disable.

**Comment by yiminc** [comment]
Closing this issue as the root cause has been resolved in newer versions.

## Summary
The panic was caused by `service/history/shard/compatibility.go` which attempted to validate persisted queue states on shard load. When archival was previously enabled (creating queue category ID 5 in shard metadata) and then disabled in config, the compatibility check couldn't find the category in the registry and panicked.

## Resolution
The `compatibility.go` file was removed in PR #4616 (v1.22+), which eliminates this panic scenario.

## Guidance for users still on 1.21.x
If you need to upgrade from 1.20.x to 1.21.x with archival previously enabled, use the workaround provided by @yycptt:
1. Set `history.archivalProcessorSchedulerWorkerCount` dynamic config to 0
2. Optionally set `history.queuePendingTasksMaxCount` to a lower value (e.g., 1000)
3. Re-enable archival in static config
4. Deploy 1.21, then 1.22
5. Revert config changes and restart

Alternatively, upgrading directly from 1.20.x to 1.22+ should avoid this issue entirely.
