### ISSUE TITLE
Make server stacktraces more readable during debugging

### ISSUE THREAD

**Issue by vitarb** [temporalio/temporal#664]
Currently temporal server emits all logs in json, which makes perfect sense for the production environment where all logs are uploaded to the elasticsearch, but at the same time it makes local development and debugging very painful.

Take a look at this stack trace for example to see how hard it is to read it as a plain text:
```
{"level":"error","ts":"2020-08-08T18:58:04.640-0700","msg":"Panic is captured","service":"history","sys-stack-trace":"goroutine 1000726 [running]:\nruntime/debug.Stack(0x0, 0x0, 0x0)\n\t/usr/lib/go/src/runtime/debug/stack.go:24 +0xa1\ngo.temporal.io/server/common/log.CapturePanic(0x319c260, 0xc00048d230, 0xc0010f32e8)\n\t/home/user/projects/temporal/common/log/panic.go:49 +0xf5\npanic(0x279a960, 0x4266350)\n\t/usr/lib/go/src/runtime/panic.go:975 +0x41b\ngo.temporal.io/server/service/history.(*workflowResetorImpl).buildNewMutableStateForReset(0xc000f13520, 0x318d9c0, 0xc00176dcb0, 0xc0001dd030, 0x31d6b40, 0xc000f5c240, 0x31d6b40, 0xc000f5c240, 0xc001a8eed0, 0x9, ...)\n\t/home/user/projects/temporal/service/history/workflowResetor.go:295 +0x5f4\ngo.temporal.io/server/service/history.(*workflowResetorImpl).ResetWorkflowExecution(0xc000f13520, 0x318d9c0, 0xc00176dcb0, 0xc0006a8c80, 0x31b6520, 0xc000ec4d80, 0x31d6b40, 0xc000f5c240, 0x31b6520, 0xc000ec4d80, ...)\n\t/home/user/projects/temporal/service/history/workflowResetor.go:124 +0x6a9\ngo.temporal.io/server/service/history.(*historyEngineImpl).ResetWorkflowExecution(0xc0011f0400, 0x318d9c0, 0xc00176dcb0, 0xc000f43020, 0x0, 0x0, 0x0)\n\t/home/user/projects/temporal/service/history/historyEngine.go:2370 +0x12c6\ngo.temporal.io/server/service/history.(*Handler).ResetWorkflowExecution(0xc000646320, 0x318d9c0, 0xc00176dcb0, 0xc000f43020, 0x0, 0x0, 0x0)\n\t/home/user/projects/temporal/service/history/handler.go:1102 +0x62b\ngo.temporal.io/server/service/history.(*NilCheckHandler).ResetWorkflowExecution(0xc000e7a710, 0x318d9c0, 0xc00176dcb0, 0xc000f43020, 0x0, 0x0, 0x0)\n\t/home/user/projects/temporal/service/history/nilCheckHandler.go:185 +0x90\ngo.temporal.io/server/api/historyservice/v1._HistoryService_ResetWorkflowExecution_Handler.func1(0x318d9c0, 0xc00176dcb0, 0x29f14c0, 0xc000f43020, 0x0, 0x0, 0x0, 0x0)\n\t/home/user/projects/temporal/api/historyservice/v1/service.pb.go:1157 +0x10b\ngo.temporal.io/server/service/history.interceptor(0x318d9c0, 0xc00176dcb0, 0x29f14c0, 0xc000f43020, 0xc000f43060, 0xc000f43080, 0x0, 0x0, 0x0, 0x0)\n\t/home/user/projects/temporal/service/history/service.go:580 +0x95\ngo.temporal.io/server/api/historyservice/v1._HistoryService_ResetWorkflowExecution_Handler(0x2a7dde0, 0xc000e7a710, 0x318d9c0, 0xc00176dcb0, 0xc000f58ae0, 0x2b7f830, 0x0, 0x0, 0x0, 0x0)\n\t/home/user/projects/temporal/api/historyservice/v1/service.pb.go:1159 +0x24d\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc0014e01c0, 0x31a6d00, 0xc002114a80, 0xc00151a400, 0xc00159e5d0, 0x427a880, 0x0, 0x0, 0x0)\n\t/home/user/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:1180 +0x104d\ngoogle.golang.org/grpc.(*Server).handleStream(0xc0014e01c0, 0x31a6d00, 0xc002114a80, 0xc00151a400, 0x0)\n\t/home/user/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:1503 +0x98e\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001f53390, 0xc0014e01c0, 0x31a6d00, 0xc002114a80, 0xc00151a400)\n\t/home/user/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:843 +0xf4\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/home/user/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:841 +0x2b7\n","error":"runtime error: invalid memory address or nil pointer dereference","logging-call-at":"panic.go:51","stacktrace":"go.temporal.io/server/common/log/loggerimpl.(*loggerImpl).Error\n\t/home/user/projects/temporal/common/log/loggerimpl/logger.go:138\ngo.temporal.io/server/common/log.CapturePanic\n\t/home/user/projects/temporal/common/log/panic.go:51\nruntime.gopanic\n\t/usr/lib/go/src/runtime/panic.go:975\nruntime.panicmem\n\t/usr/lib/go/src/runtime/panic.go:212\nruntime.sigpanic\n\t/usr/lib/go/src/runtime/signal_unix.go:695\ngo.temporal.io/server/service/history.(*workflowResetorImpl).buildNewMutableStateForReset\n\t/home/user/projects/temporal/service/history/workflowResetor.go:295\ngo.temporal.io/server/service/history.(*workflowResetorImpl).ResetWorkflowExecution\n\t/home/user/projects/temporal/service/history/workflowResetor.go:124\ngo.temporal.io/server/service/history.(*historyEngineImpl).ResetWorkflowExecution\n\t/home/user/projects/temporal/service/history/historyEngine.go:2370\ngo.temporal.io/server/service/history.(*Handler).ResetWorkflowExecution\n\t/home/user/projects/temporal/service/history/handler.go:1102\ngo.temporal.io/server/service/history.(*NilCheckHandler).ResetWorkflowExecution\n\t/home/user/projects/temporal/service/history/nilCheckHandler.go:185\ngo.temporal.io/server/api/historyservice/v1._HistoryService_ResetWorkflowExecution_Handler.func1\n\t/home/user/projects/temporal/api/historyservice/v1/service.pb.go:1157\ngo.temporal.io/server/service/history.interceptor\n\t/home/user/projects/temporal/service/history/service.go:580\ngo.temporal.io/server/api/historyservice/v1._HistoryService_ResetWorkflowExecution_Handler\n\t/home/user/projects/temporal/api/historyservice/v1/service.pb.go:1159\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/home/user/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:1180\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/home/user/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:1503\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/home/user/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:843"}
```

As you can see not only logs are in json but entire stack traces are encoded into a single line strings with \n and \t appearing in the plain text.

We should add a mode for pretty logging, which developers can use locally when they want to have greater readability during debugging.

**Comment by yiminc** [comment]
You should be able to set the log format from default json to console. https://github.com/temporalio/temporal/blob/7cf34812ab2c09438b1cff3c2cc481a6ee711115/common/log/config.go#L36-L39
