### ISSUE TITLE
tctl admin db scan fails with panic / segmentation violation

### ISSUE THREAD

**Issue by serhii-samoilenko** [temporalio/temporal#868]
I tried to perform a db scan with tctl on the Cassandra:
`tctl adm db scan --db_address temporal-cassandra.temporal --db_port 9042`

## Expected Behavior
Successful completion of the scan

## Actual Behavior
Got message:
```
scan results located under:  ./scan_1602836287
{
        "NumberOfShardsFinished": 1,
        "TotalExecutionsCount": 0,
        "CorruptedExecutionsCount": 0,
        "ExecutionCheckFailureCount": 0,
        "NumberOfShardScanFailures": 0,
        "PercentageCorrupted": 0,
        "PercentageCheckFailure": 0,
        "Rates": {
                "TimeRunning": "7.684172ms",
                "DatabaseRPS": 130,
                "TotalDBRequests": 1,
                "ShardsPerHour": 468406,
                "ExecutionsPerHour": 0
        },
        "CorruptionTypeBreakdown": {
                "TotalHistoryMissing": 0,
                "TotalInvalidFirstEvent": 0,
                "TotalOpenExecutionInvalidCurrentExecution": 0,
                "PercentageHistoryMissing": 0,
                "PercentageInvalidStartEvent": 0,
                "PercentageOpenExecutionInvalidCurrentExecution": 0
        },
        "ShardExecutionCountsDistribution": {
                "MinExecutions": null,
                "MaxExecutions": null,
                "AverageExecutions": 0
        }
}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x133dbde]
goroutine 752 [running]:
go.temporal.io/server/common/persistence/cassandra.(*cassandraPersistence).ListConcreteExecutions(0xc00093a090, 0xc000914da0, 0xc0000483a0, 0x0, 0x0)
        /temporal/common/persistence/cassandra/cassandraPersistence.go:1881 +0x24e
go.temporal.io/server/tools/cli.scanShard(0xc00067c380, 0x1, 0xc00082f380, 0xc000643f40, 0x1f4, 0x211b780, 0x2f8a208, 0x2110560, 0xc0005cb540, 0xc0008426e0, ...)
        /temporal/tools/cli/adminDBScanCommand.go:316 +0x78c
go.temporal.io/server/tools/cli.AdminDBScan.func1(0x0, 0x4000, 0xc0003ec3d8, 0xc000889a40, 0xc00067c380, 0xc00082f380, 0xc000643f40, 0x1f4, 0x211b780, 0x2f8a208, ...)
        /temporal/tools/cli/adminDBScanCommand.go:246 +0xfb
created by go.temporal.io/server/tools/cli.AdminDBScan
        /temporal/tools/cli/adminDBScanCommand.go:243 +0x53f
```

## Steps to Reproduce the Problem

  1. Run the `tctl adm db scan` command

## Specifications

  - Version: 1.0.0, 0.29.0
  - Platform: k8s

**Comment by wxing1292** [comment]
fix merged, will be part of the next release
