### ISSUE TITLE
Support for setting max payload size

### ISSUE THREAD

**Issue by hazcod** [temporalio/temporal#961]
**Is your feature request related to a problem? Please describe.**
Sending off my HTTP request for processing results in an error.

```go
Traceback (most recent call last):
  File "github.com/hazcod/foo/proxy/service/process_response.go", line 40, in service.storeRequestResponse
  File "runtime/asm_amd64.s", line 1374, in runtime.goexit
serviceerror.ResourceExhausted: grpc: received message larger than max (13335484 vs. 4194304)
```

**Comment by samarabbas** [comment]
Passing such large objects through Temporal is an anti-pattern.  Having said that we have increased the message size on response payloads.  This should no longer be a problem.
