### ISSUE TITLE
Panic while running with postgres (CRDB 20.1.x)

### ISSUE THREAD

**Issue by robzienert** [temporalio/temporal#978]
## Expected Behavior

Services to start.

## Actual Behavior

History service panics during startup, apparently while creating a workflow execution.

```
{
  "level": "error",
  "ts": "2020-11-11T22:09:12.907Z",
  "msg": "Panic is captured",
  "service": "history",
  "sys-stack-trace": "goroutine 3798 [running]:\nruntime/debug.Stack(0x1e3d820, 0x1df0060, 0xc0003883c0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngo.temporal.io/server/common/log.CapturePanic(0x263d700, 0xc0005c1b90, 0xc000ddfa68)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/log/panic.go:49 +0x8f\npanic(0x1df0060, 0xc0003883c0)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\ngithub.com/jmoiron/sqlx/reflectx.mustBe(0x7fe9e8724f40, 0x1d0dea0, 0x19)\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/reflectx/reflect.go:249 +0xc4\ngithub.com/jmoiron/sqlx/reflectx.(*Mapper).TraversalsByNameFunc(0xc0004500c0, 0x2662c60, 0x1d0dea0, 0xc000c38c80, 0x4, 0xa, 0xc000dde0c0, 0x0, 0x7aadbc)\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/reflectx/reflect.go:187 +0x88\ngithub.com/jmoiron/sqlx.bindArgs(0xc000c38c80, 0x4, 0xa, 0x1d0dea0, 0xc000388380, 0xc0004500c0, 0xc000c38c80, 0x4, 0xa, 0x0, ...)\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:166 +0x2a0\ngithub.com/jmoiron/sqlx.bindStruct(0x2, 0x21ea9f2, 0x77, 0x1d0dea0, 0xc000388380, 0xc0004500c0, 0xc00160fec0, 0x203000, 0x203000, 0x203000, ...)\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:203 +0xf9\ngithub.com/jmoiron/sqlx.bindNamedMapper(0x2, 0x21ea9f2, 0x77, 0x1d0dea0, 0xc000388380, 0xc0004500c0, 0xc, 0x0, 0x8, 0x18, ...)\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:333 +0x120\ngithub.com/jmoiron/sqlx.NamedExec(0x2643a00, 0xc0015d4f60, 0x21ea9f2, 0x77, 0x1d0dea0, 0xc000388380, 0x20, 0x1da8380, 0xc000afb501, 0xc000388380)\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:351 +0xf9\ngithub.com/jmoiron/sqlx.(*Tx).NamedExec(0xc0015d4f60, 0x21ea9f2, 0x77, 0x1d0dea0, 0xc000388380, 0xc00011b260, 0x1, 0xc0001a0df8, 0xc000388301)\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/sqlx.go:421 +0x66\ngo.temporal.io/server/common/persistence/sql/sqlplugin/postgresql.(*db).InsertIntoTransferTasks(0xc0015d4f90, 0xc000b9f380, 0x1, 0x1, 0xc6, 0xc6, 0x0, 0x0)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlplugin/postgresql/execution.go:245 +0x85\ngo.temporal.io/server/common/persistence/sql.createTransferTasks(0x267ab80, 0xc0015d4f90, 0xc00165ab30, 0x1, 0x1, 0x4, 0xc00004bb60, 0x24, 0xc001678060, 0x17, ...)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManagerUtil.go:733 +0x4a1\ngo.temporal.io/server/common/persistence/sql.applyTasks(0x267ab80, 0xc0015d4f90, 0xc000000004, 0xc00004bb60, 0x24, 0xc001678060, 0x17, 0xc00163a6c0, 0x24, 0xc00165ab30, ...)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManagerUtil.go:476 +0xcd\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).applyWorkflowSnapshotTxAsNew(0xc000bbaba0, 0x267ab80, 0xc0015d4f90, 0xc000000004, 0xc0015be708, 0x10, 0x10)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManagerUtil.go:391 +0x2c4\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).createWorkflowExecutionTx(0xc000bbaba0, 0x267ab80, 0xc0015d4f90, 0xc0015be6e0, 0x14d2d7c, 0x1f89340, 0xc0015d4f90)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManager.go:205 +0x56e\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).CreateWorkflowExecution.func1(0x267ab80, 0xc0015d4f90, 0xc000000004, 0xf3)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManager.go:99 +0x5d\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).txExecuteShardLocked.func1(0x267ab80, 0xc0015d4f90, 0xc0015d4f90, 0x0)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManager.go:82 +0x82\ngo.temporal.io/server/common/persistence/sql.(*sqlStore).txExecute(0xc000bbaba0, 0x216b266, 0x17, 0xc000ddee18, 0x1, 0xc000ddee40)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/common.go:63 +0x1b6\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).txExecuteShardLocked(0xc000bbaba0, 0x216b266, 0x17, 0xf3, 0xc000ddee80, 0x0, 0xc000ddeea8)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManager.go:78 +0x84\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).CreateWorkflowExecution(0xc000bbaba0, 0xc0015be6e0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManager.go:98 +0xb5\ngo.temporal.io/server/common/persistence.(*executionManagerImpl).CreateWorkflowExecution(0xc000bbabd0, 0xc0015be580, 0xc00049a1c0, 0x13, 0x2163dd7)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/executionStore.go:372 +0xf7\ngo.temporal.io/server/common/persistence.(*workflowExecutionRateLimitedPersistenceClient).CreateWorkflowExecution(0xc000bbac00, 0xc0015be580, 0x16, 0xbfe33613ef8d26a0, 0x151a4c425)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/persistenceRateLimitedClients.go:220 +0x5f\ngo.temporal.io/server/common/persistence.(*workflowExecutionPersistenceClient).CreateWorkflowExecution(0xc000bbac30, 0xc0015be580, 0xc001678060, 0x17, 0xc00165ab30)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/persistenceMetricClients.go:246 +0xd3\ngo.temporal.io/server/service/history.(*shardContextImpl).CreateWorkflowExecution(0xc00065fb00, 0xc0015be580, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/shardContext.go:486 +0x2c9\ngo.temporal.io/server/service/history.(*workflowExecutionContextImpl).createWorkflowExecutionWithRetry.func1(0x1f87000, 0xc0015d26c0)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/workflowExecutionContext.go:953 +0x45\ngo.temporal.io/server/common/backoff.Retry(0xc000ddf208, 0x25e9c20, 0xc0004b42d0, 0x2204960, 0xbfe33613df667097, 0x1417e0e16)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/backoff/retry.go:103 +0xf0\ngo.temporal.io/server/service/history.(*workflowExecutionContextImpl).createWorkflowExecutionWithRetry(0xc001732820, 0xc0015be580, 0xc000e7bc00, 0xc001678060, 0xc00163a6c0)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/workflowExecutionContext.go:957 +0xaa\ngo.temporal.io/server/service/history.(*workflowExecutionContextImpl).createWorkflowExecution(0xc001732820, 0xc00161d9e0, 0x13e, 0x1f650be3, 0xed73e57cf, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/workflowExecutionContext.go:394 +0x169\ngo.temporal.io/server/service/history.(*historyEngineImpl).StartWorkflowExecution(0xc00000c3c0, 0x262be80, 0xc00165cff0, 0xc001657bd0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/historyEngine.go:599 +0x5a4\ngo.temporal.io/server/service/history.(*Handler).StartWorkflowExecution(0xc000524280, 0x262be80, 0xc00165cff0, 0xc001657bd0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/handler.go:666 +0x2b9\ngo.temporal.io/server/service/history.(*NilCheckHandler).StartWorkflowExecution(0xc000f64fe0, 0x262be80, 0xc00165cff0, 0xc001657bd0, 0xc000f64fe0, 0x30, 0xc0006cca80)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/nilCheckHandler.go:57 +0x58\ngo.temporal.io/server/api/historyservice/v1._HistoryService_StartWorkflowExecution_Handler.func1(0x262be80, 0xc00165cff0, 0x20db000, 0xc001657bd0, 0xc000c06b30, 0x40ec08, 0x20, 0x1e988c0)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/api/historyservice/v1/service.pb.go:857 +0x89\ngo.temporal.io/server/common/rpc.Interceptor(0x262be80, 0xc00165cff0, 0x20db000, 0xc001657bd0, 0xc00164f460, 0xc00164f480, 0xc000c06ba0, 0x4fe418, 0x1fb89e0, 0xc00165cff0)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/rpc/interceptor.go:35 +0x55\ngo.temporal.io/server/api/historyservice/v1._HistoryService_StartWorkflowExecution_Handler(0x20ff3e0, 0xc000f64fe0, 0x262be80, 0xc00165cff0, 0xc0016446c0, 0x2204ab8, 0x262be80, 0xc00165cff0, 0xc00167e2c0, 0x14b)\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/api/historyservice/v1/service.pb.go:859 +0x14b\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc000ee8700, 0x264a480, 0xc001628180, 0xc0007bfc00, 0xc000f63e00, 0x36d8280, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.33.0/server.go:1210 +0x50a\ngoogle.golang.org/grpc.(*Server).handleStream(0xc000ee8700, 0x264a480, 0xc001628180, 0xc0007bfc00, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.33.0/server.go:1533 +0xcfd\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00164dff0, 0xc000ee8700, 0x264a480, 0xc001628180, 0xc0007bfc00)\n\t/go/pkg/mod/google.golang.org/grpc@v1.33.0/server.go:871 +0xa1\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.33.0/server.go:869 +0x204\n",
  "error": "reflect: call of github.com/jmoiron/sqlx/reflectx.(*Mapper).TraversalsByNameFunc on slice Value",
  "logging-call-at": "panic.go:51",
  "stacktrace": "go.temporal.io/server/common/log/loggerimpl.(*loggerImpl).Error\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/log/loggerimpl/logger.go:138\ngo.temporal.io/server/common/log.CapturePanic\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/log/panic.go:51\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:969\ngithub.com/jmoiron/sqlx/reflectx.mustBe\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/reflectx/reflect.go:249\ngithub.com/jmoiron/sqlx/reflectx.(*Mapper).TraversalsByNameFunc\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/reflectx/reflect.go:187\ngithub.com/jmoiron/sqlx.bindArgs\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:166\ngithub.com/jmoiron/sqlx.bindStruct\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:203\ngithub.com/jmoiron/sqlx.bindNamedMapper\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:333\ngithub.com/jmoiron/sqlx.NamedExec\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/named.go:351\ngithub.com/jmoiron/sqlx.(*Tx).NamedExec\n\t/go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/sqlx.go:421\ngo.temporal.io/server/common/persistence/sql/sqlplugin/postgresql.(*db).InsertIntoTransferTasks\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlplugin/postgresql/execution.go:245\ngo.temporal.io/server/common/persistence/sql.createTransferTasks\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManagerUtil.go:733\ngo.temporal.io/server/common/persistence/sql.applyTasks\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManagerUtil.go:476\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).applyWorkflowSnapshotTxAsNew\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManagerUtil.go:391\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).createWorkflowExecutionTx\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManager.go:205\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).CreateWorkflowExecution.func1\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManager.go:99\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).txExecuteShardLocked.func1\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManager.go:82\ngo.temporal.io/server/common/persistence/sql.(*sqlStore).txExecute\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/common.go:63\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).txExecuteShardLocked\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManager.go:78\ngo.temporal.io/server/common/persistence/sql.(*sqlExecutionManager).CreateWorkflowExecution\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/sql/sqlExecutionManager.go:98\ngo.temporal.io/server/common/persistence.(*executionManagerImpl).CreateWorkflowExecution\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/executionStore.go:372\ngo.temporal.io/server/common/persistence.(*workflowExecutionRateLimitedPersistenceClient).CreateWorkflowExecution\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/persistenceRateLimitedClients.go:220\ngo.temporal.io/server/common/persistence.(*workflowExecutionPersistenceClient).CreateWorkflowExecution\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/persistence/persistenceMetricClients.go:246\ngo.temporal.io/server/service/history.(*shardContextImpl).CreateWorkflowExecution\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/shardContext.go:486\ngo.temporal.io/server/service/history.(*workflowExecutionContextImpl).createWorkflowExecutionWithRetry.func1\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/workflowExecutionContext.go:953\ngo.temporal.io/server/common/backoff.Retry\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/backoff/retry.go:103\ngo.temporal.io/server/service/history.(*workflowExecutionContextImpl).createWorkflowExecutionWithRetry\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/workflowExecutionContext.go:957\ngo.temporal.io/server/service/history.(*workflowExecutionContextImpl).createWorkflowExecution\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/workflowExecutionContext.go:394\ngo.temporal.io/server/service/history.(*historyEngineImpl).StartWorkflowExecution\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/historyEngine.go:599\ngo.temporal.io/server/service/history.(*Handler).StartWorkflowExecution\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/handler.go:666\ngo.temporal.io/server/service/history.(*NilCheckHandler).StartWorkflowExecution\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/service/history/nilCheckHandler.go:57\ngo.temporal.io/server/api/historyservice/v1._HistoryService_StartWorkflowExecution_Handler.func1\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/api/historyservice/v1/service.pb.go:857\ngo.temporal.io/server/common/rpc.Interceptor\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/common/rpc/interceptor.go:35\ngo.temporal.io/server/api/historyservice/v1._HistoryService_StartWorkflowExecution_Handler\n\t/go/pkg/mod/go.temporal.io/server@v1.2.1/api/historyservice/v1/service.pb.go:859\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.33.0/server.go:1210\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.33.0/server.go:1533\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.33.0/server.go:871"
}
```

## Steps to Reproduce the Problem

  1. Running CRDB V20.1.8.1
  1. Start all services.

## Specifications

  - Version: 1.2.1
  - Platform: Ubuntu (running binaries directly; not Docker images)

Using configuration lifted from https://github.com/temporalio/temporal/tree/master/config (`development_postgres.yaml` and empty `dynamicconfig` file).

**Comment by wxing1292** [comment]
Tried CRDB 20.2 on my macbook, cannot reproduce the issue with either actual workflow or SQL layer tests.
Can you plz provide more info?

**Comment by wxing1292** [comment]
One more question, are you using the Temporal as is, or is there anything changed in go.mod?
specifically
1. github.com/jmoiron/sqlx
2. github.com/go-sql-driver/mysql
3. github.com/lib/pq
4. github.com/mattn/go-sqlite3

**Comment by wxing1292** [comment]
the v1.2.1 still use a temporal workaround on sqlx, make sure when using Temporal as dependency, override this
```
// TODO https://github.com/uber/cadence/issues/2863
replace github.com/jmoiron/sqlx v1.2.0 => github.com/longquanzheng/sqlx v0.0.0-20191125235044-053e6130695c
```
ref: https://github.com/temporalio/temporal/blob/v1.2.1/go.mod#L79-L90

**Comment by robzienert** [comment]
Ah-ha! I wasn't aware of the `replace` rule. Adding that fixed things. Thanks!
